config/routes.rb
Healclick::Application.routes.draw do

  get '/treatments/:treatment_summary_id', to: redirect('/treatments/%{treatment_summary_id}/reviews')
  get '/doctors/:doctor_summary_id', to: redirect('/doctors/%{doctor_summary_id}/reviews')

  Redirect.all.each do |redir|
    get redir.from, to: redirect(redir.to)
  end
  post 'questionnaire/save_categories'
  post 'questionnaire/next_question'
  mount_roboto
  get 'system_settings/create'
  get 'system_settings/update'
  put 'system_settings/points_save'
  get 'time_series_analysis', to: 'users#time_series_analysis'
  get 'time_series_analysis_admin', to: 'users#time_series_analysis_admin'
  get 'main', to: 'home#index', post_type: 'any', as: 'everything'
  get 'topics', to: 'home#index', post_type: 'all_topics'
  get 'medical-topics', to: 'home#index', post_type: 'medical_topics', as: 'medical_topics'
  get 'social-topics', to: 'home#index', post_type: 'social_topics', as: 'social_topics'
  get 'fun-stuff', to: 'home#index', post_type: 'fun_stuff', as: 'fun_stuff'
  get 'introductions', to: 'home#index', post_type: 'introductions'
  get 'faq', to: 'home#index', post_type: 'faq'
  get 'blog', to: 'home#index', post_type: 'blog'
  get 'conditions/autocomplete', to: 'conditions#autocomplete'
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  devise_for :users, path_names: {sign_in: 'login', sign_out: 'logout' }, controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations' }

  resources :posts do
    get :post_body, on: :member
    get :mark_as_helpful, on: :member
    get :follow, on: :member
    get :unfollow, on: :member
    get :luv, on: :member
    get :say_something, on: :collection
    get :expand_replies, on: :member
    resources :comments do
      resources :comments
      get :mark_as_helpful, on: :member
      get :luv, on: :member
    end
  end

  resources :noindex_rules, only: [:create, :destroy]

  resources :comments do
    get :mark_as_helpful, on: :member
    get :luv, on: :member
  end

  get '/reviews/summary', to: redirect('/treatments')
  resources :reviews do
    get :interest, on: :member
  end
  get '/treatments', to: 'reviews#summary', as: :summary_reviews

  resources :notifications do 
    get :read, on: :member
    get :mark_all_as_read, on: :collection
    delete :delete_all, on: :collection
  end

  resources :messages do 
    get :sent, on: :collection
    get :mark_all_as_read, on: :collection
    delete :delete_all, on: :collection
    delete :delete_all_sent, on: :collection
  end

  resources :users do 
    get :autocomplete, :on => :collection
    get :favorited_me, on: :member
    get :my_favorites, on: :member
    get :follow, on: :member
    get :unfollow, on: :member
    get :luv, on: :member
    get :leaderboard, on: :collection
    get :ranking, on: :collection
    get :favorite_list, on: :collection
    resources :photos do
      get :set_as_profile, on: :member    
      resources :comments
    end
    get :map, on: :collection
  end

  resources :photos do
    get :set_as_profile, on: :member
    resources :comments
  end

  resources :user_conditions

  resources :symptoms do 
    get :autocomplete, :on => :collection
    get :set_level, on: :member
    get :set_period, on: :member
    post :batch_create, on: :collection
    patch :batch_update, on: :collection
    post :popular_symptoms, on: :collection
    delete :batch_delete, on: :collection
  end

  resources :treatments do 
    get :autocomplete, :on => :collection
    get :set_level, on: :member
    get :set_period, on: :member
    put :set_type, on: :member
    resources :treatment_reviews
    post :batch_create, on: :collection
    patch :batch_update, on: :collection
    delete :batch_delete, on: :collection
  end

  resources :doctors do
    get :autocomplete, on: :collection
    post :batch_create, on: :collection
  end

  resources :treatment_reviews do
    get :autocomplete, :on => :collection
    get :check_unique_name, on: :collection
  end
  resources :doctor_reviews do
    # get :summary, on: :collection
    get :check_unique_name, on: :collection
  end


  get '/treatments/:treatment_summary_id/reviews/:id', to: 'posts#show', as: :treatment_summary_review
  get '/treatments/:treatment_summary_id/reviews', to: 'reviews#index', as: :treatment_summary_reviews
  get '/doctors/:doctor_summary_id/reviews/:id', to: 'posts#show', as: :doctor_summary_review_path
  get '/doctors/:doctor_summary_id/reviews', to: 'doctor_reviews#summary', as: :summary_doctor_reviews
  get '/treatment_summaries/:treatment_summary_id/reviews', to: 'reviews#old_routes', as: :old_routes

  resource :tracker, controller: :tracker do
    get :treatments, on: :collection
    get :symptoms, on: :collection
    get :well_being, on: :collection
  end

  get '/profile/:username', to: 'personal_profiles#show', as: :profile, constraints: {username: /.*/}

  get '/activity/:username', to: 'personal_profiles#activity', as: :activity, constraints: {username: /.*/}

  resource :personal_profile do
    get :select_main_condition, on: :member
    get :basic_info, on: :member
    get :my_health, on: :member
    get :profile_photo, on: :member
    get :symptoms, on: :member
    get :treatments, on: :member
    get :crop_photo, on: :member
    get :bookmarks, on: :member
    get :my_topics, on: :member
    get :symptoms_chart, on: :member
    patch :crop_photo, on: :member
  end

  resources :labs, only: [:update] do
    get :autocomplete, on: :collection
    get :change_date, on: :collection
    delete :batch_delete, on: :collection
    post :batch_create, on: :collection
  end

  resources :events, :only => [:update, :create, :show, :index]

  get 'settings', to: 'settings#index', as: :settings
  patch 'settings', to: 'settings#index', as: :post_settings

  post 'settings/set', to: 'settings#set', as: 'set_setting'

  resources :system_settings

  get 'home', to: 'home#new_home', as: :home
  get 'guest_sidebar', to: 'home#guest_sidebar'

  get 'skip_to_dashboard', to: 'home#skip', as: :skip_to_dashboard

  get 'my_click', to: 'my_click#index', as: :my_click
  get 'conditions/:condition_id', to: 'home#index', as: :conditions

  get 'landing', to: 'main#index', as: :landing
  get 'run_digest', to: 'main#run_digest'
  
  root to: 'home#new_home'

  # Error
  get '404', to: 'errors#index_404'
  get '500', to: 'errors#index_500'
end

RailsAdmin::Engine.routes.draw do
  get 'noindex_rules/destroy'
  get 'noindex_rules/create'
  get 'questionnaire/save_categories'
  get 'questionnaire/next_question'
  mount_roboto
  controller 'main' do
    scope ':model_name' do
      post 'bulk_edit_reviews', :to => :bulk_edit_reviews, :as => 'bulk_edit_reviews'
      post 'bulk_edit_treatments', :to => :bulk_edit_treatments, :as => 'bulk_edit_treatments'

      # Merge Treatment Summaries
      post 'bulk_edit_treatment_summaries', :to => :bulk_edit_treatment_summaries, :as => 'bulk_edit_treatment_summaries'
      get 'bulk_edit_treatment_summaries', :to => :get_bulk_edit_treatment_summaries, :as => 'get_bulk_edit_treatment_summaries'

      # Merge Symptoms Summaries
      post 'bulk_merge_symptom_summaries', :to => :bulk_merge_symptom_summaries, :as => 'bulk_merge_symptom_summaries'
      get 'bulk_merge_symptom_summaries', :to => :get_bulk_merge_symptom_summaries, :as => 'get_bulk_merge_symptom_summaries'
    end
  end
end

app/controllers/treatments_controller.rb
class TreatmentsController < ApplicationController

  before_filter :authenticate_user!, :find_treatment, :find_tracking_date
  skip_before_filter :check_profile, :only => [:autocomplete, :create, :set_level, :set_period, :batch_create]

  def autocomplete
    if params[:query].length >= 3
      @treatments = TreatmentSummary.search(params[:query]).where('reviews_count > 0').order('reviews_count DESC')
    else
      @treatments = []
    end

    render json: @treatments.try(:names_with_counts)
  end

  def create
    render text: 'ok' if treatment_params[:treatment].blank?

    @treatment = current_user.treatments.new(treatment_params)
    unless @treatment.save
      @error = 'User condition could not be saved.'
      render 'errors/error.js'
    end
  end

  def edit
  end

  def update
    @treatment.update_attributes(treatment_params)
  end

  def batch_create
    @errors = nil
    @treatments = []
    @date = Date.parse(params.fetch(:date, Time.zone.now.to_date.to_s)) unless params[:date].blank?
    treatment_params[:treatment].split(',').reverse.each do |treatment|
      treatment = Treatment.new treatment: treatment, user_id: current_user.id, skip_review_update: true
      if treatment.valid?
        treatment[:user_id] = current_user.id
        treatment.save
        @treatments << treatment
      else
        @errors = treatment.errors.try(:[], :treatment).try(:first) if @errors.nil?
      end
    end
  end

  def batch_update
    if @tracking_date.today?
      current_user.update_attributes batch_treatment_params
    else
      batch_treatment_params[:treatments_attributes].values.each do |attrs|
        treatment = current_user.treatments.find attrs[:id]
        treatment.update_attributes attrs
        treatment.update_treatment_log
      end
    end
    @desired_path = my_health_personal_profile_path(medical_editor: :treatments)
    @finished = params[:finished] == 'true'
    @js_redirect = params[:commit] == "Track More Treatments"
    respond_to do |format|
      format.html { redirect_to @desired_path }
      format.js { render 'symptoms/batch_update' }
    end    
  end

  def batch_delete
    params[:ids].split(',').each do |id|
      treatment = Treatment.find_by_id(id)
      summary = treatment.treatment_summary
      treatment.destroy
      summary.reload_numbers
    end
  end

  def set_level
    if @treatment.treatment_review.nil?
      @treatment.hide_for_feed = true
      @treatment.create_review
    end
    @treatment.update_attributes(level: params[:level])
    @treatment.update_treatment_summary
  end

  def set_period
    @treatment.update_attributes(period: params[:period])
    @treatment.update_treatment_summary
    render text: 'ok'
  end

  def set_type
    @treatment.update_attributes treatment_type: params[:type]
    render text: 'ok'
  end

  def destroy
    summary = @treatment.treatment_summary
    @treatment.destroy
    @treatment_id = @treatment.id
    summary.reload_numbers
  end

  def find_treatment
    @treatment = current_user.treatments.find(params[:id]) if params[:id].present?
  end

  def treatment_params
    params.require(:treatment).permit(:treatment, :level, :condition_id, :treatment_type, :currently_taking)
  end

  def batch_treatment_params
    prms = params.require(:user).permit(treatments_attributes: [:id, :take_today, :current_dose, :rank, :currently_taking])
    prms[:treatments_attributes].each do |key, attrs|
      attrs[:last_taken_at] = @tracking_date if attrs[:take_today] == '1'
      attrs[:tracking_date] = @tracking_date
    end
    prms
  end

  def find_tracking_date
    @tracking_date = Date.parse(params.fetch(:tracking_date, Time.zone.now.to_date.to_s))
    @date = @tracking_date
  end

end

app/helpers/treatments_helper.rb
module TreatmentsHelper
  def treatment_period(treatment)
    [l(treatment.started_on, format: :month_year), treatment.currently_taking? ? 'Current' : l((treatment.ended_on || Date.today), format: :month_year)].join(' - ')
  end

  def user_treatments_for_chart_filter(user)
    options_for_select([['Events', 'events'], ['No Treatment', 0, {'data-start' => nil, 'data-end' => nil}]] + user.treatments.map {|treatment|
      [treatment.treatment, treatment.id, {'data-start' => treatment.started_on, 'data-end' => treatment.ended_on}]
    })
  end

  def restore_treatment_values(treatment, date)
    date = Date.parse(date.to_s) if date.present?
    if date.present? && date <= Time.zone.now.to_date
      treatment_log = treatment.treatment_logs.order('treatment_logs.date desc').where('treatment_logs.date = ?', date).first.try(:attributes)
    end
    treatment_log ||= {}
    treatment_log.symbolize_keys
  end

  def options_for_graph(user = current_user)
    currently_taking = user.treatments.by_rank.currently_taking.map {|t| [t.treatment, t.id, {'data-start' => t.started_on, 'data-end' => t.ended_on}]}
    not_taking = user.treatments.by_rank.not_currently_taking.map {|t| [t.treatment, t.id, {'data-start' => t.started_on, 'data-end' => t.ended_on}]}
    options_for_select [['Select treatment', '']] + currently_taking + not_taking
  end

  def show_currently_taking?
    return false unless @date
    @date.to_date == Time.now.in_time_zone.to_date || @date.to_date == 1.day.from_now.in_time_zone.to_date
  end

  def labs_options_for_graph(user = current_user)
    options_for_select [['Select labs and other metrics', '']] + user.labs.map {|l| [l.name, l.id]}
  end

end

app/views/treatments/_edit_name.html.haml
.modal.hide.fade#edit-treatment-name-modal
  .modal-header
    %button.close{'data-dismiss' => :modal} &times;
    %h3 Edit Treatment Name
  = form_for @treatment, remote: true do |f|
    .modal-body
      = f.label :treatment, 'Treatment Name'
      = f.text_field :treatment, style: "width: 95%"
    .modal-footer
      = f.submit 'Save', class: 'btn btn-success', 'data-disable-with' => 'Loading...'

app/views/treatments/_tracker_fields.html.haml
- restore_values = restore_treatment_values(form.object, date)
.form-group.no-gutter
  = form.hidden_field :id
  - form.object.take_today = restore_values.fetch(:take_today, false)
  .take-today-select{class: "#{restore_values.fetch(:take_today, false) ? 'checked' : ''}"}
  .hide
    = form.check_box :take_today, class: 'take-today-checkbox'
  = form.text_field :current_dose, placeholder: 'Enter dosage', class: 'form-control current-dose', value: restore_values.fetch(:current_dose, form.object.current_dose)
  - if treatment.treatment_review.try(:review).present?
    = link_to 'Edit Review', edit_review_path(treatment.treatment_review.review), remote: true
  - else
    = link_to 'Add Review', new_review_path(treatment_id: treatment.id), remote: true

app/views/treatments/_treatment.html.haml
- treatment_review = treatment.treatment_review.nil? ? treatment.build_treatment_review : treatment.treatment_review
- date ||= @date
- date ||= Time.zone.now.to_date
%div{id: "treatment_#{treatment.id}"}
  = f.fields_for :treatments, treatment do |ff|
    .row.treatment{data: {'treatment-id' => treatment.id}}
      = hidden_field_tag :tracking_date, date

      - if show_currently_taking?
        .col-lg-1.col-md-1.col-sm-1
          = radio_button_tag "bulk_edit_id_#{treatment.id}", treatment.id, false, class: 'bulk-edit-radio'
      .treatment.col-lg-2.col-md-2.col-sm-2.col-xs-12
        = link_to treatment.treatment, summary_reviews_path(treatment_name: treatment.treatment, commit: 'Search'), target: :_blank
      .taken-today.col-lg-1.col-md-1.col-sm-1.col-xs-12

        - restore_values = restore_treatment_values(ff.object, date)
        - ff.object.take_today = restore_values.fetch(:take_today, false)
        .visible-xs
          %br
          .pull-left
            Taken Today?
        = link_to (ff.object.take_today ? 'Yes' : '?'), '#', class: "label label-default taken-link #{('label-info' if ff.object.take_today)}"
        = ff.check_box :take_today, class: 'take-today-checkbox hide'

      .dosage.col-lg-2.col-md-2.col-sm-2.col-xs-12
        = ff.text_field :current_dose, class: 'form-control current-dose', placeholder: 'Enter Dosage', value: restore_values.fetch(:current_dose, ff.object.current_dose)

      .rating.col-lg-2.col-md-2.col-sm-2.col-xs-12
        - if ff.object.level.blank?
          - if treatment_review.review.present?
            = link_to 'Add Rating', edit_review_path(treatment_review.review, date: date), remote: true
          - else
            = link_to 'Add Rating', new_review_path(treatment_id: treatment.id), class: 'treatment_review_link', remote: true
        - else
          .mobile-label.visible-xs
            %br
            Overall Rating:
            = ff.object.level.try(:humanize).try(:titleize)
            %br
          .hidden-xs
            = ff.object.level.try(:humanize).try(:titleize)
      .reviews.col-lg-4.col-md-4.col-sm-4.col-xs-12.treatment-edit-show-margin
        - if treatment.treatment_review.content.present?
          = link_to edit_review_path(treatment_review.review, date: date), remote: true, class: 'btn btn-success btn-xs' do
            Edit
          = link_to post_review_path_helper(treatment_review.review), target: :_blank, class: 'btn btn-success btn-xs' do
            Show
        - else
          = link_to 'Post Review', new_review_path(treatment_id: treatment.id), class: 'treatment_review_link', remote: true

app/views/treatments/_treatment_columns.html.haml
%td
  = link_to "<span class='icon-remove-circle'></span>".html_safe, treatment_path(treatment, format: :js), method: :delete, confirm: 'Are you sure you want to remove this treatment?', remote: true
%td.treatment
  = link_to treatment.treatment, summary_reviews_path(treatment_name: treatment.treatment), target: :_blank
  = link_to edit_treatment_path(treatment), remote: true, class: 'edit-treatment-name' do
    %i.icon-pencil
%td.selector
  = link_to 'Much<br/>Worse'.html_safe, set_level_treatment_path(treatment, level: 'much_worse'), class: "centered label #{treatment.level == 'much_worse' ? "label-info" : ""}", remote: true
  = link_to 'Little<br/>Worse'.html_safe, set_level_treatment_path(treatment, level: 'little_worse'), class: "centered label #{treatment.level == 'little_worse' ? "label-info" : ""}", remote: true
  = link_to 'No<br/>Change'.html_safe, set_level_treatment_path(treatment, level: 'no_change'), class: "centered label #{treatment.level == 'no_change' ? "label-info" : ""}", remote: true
  = link_to 'Little<br/>Better'.html_safe, set_level_treatment_path(treatment, level: 'little_better'), class: "centered label #{treatment.level == 'little_better' ? "label-info" : ""}", remote: true
  = link_to 'Much<br/>Better'.html_safe, set_level_treatment_path(treatment, level: 'much_better'), class: "centered label #{treatment.level == 'much_better' ? "label-info" : ""}", remote: true
  = hidden_field_tag 'string_value', treatment.load_numeric_level, class: 'text-value'
%td.dosage
  = link_to edit_modal_path, remote: true do
    - if treatment.current_dose.present?
      = treatment.current_dose
    - else
      Add Dosage
%td.dates
  = link_to edit_modal_path, remote: true do
    - if treatment.started_on.present?
      = treatment_period treatment
    - else
      Add Dates
%td
  - if treatment.treatment_review.content.present?
    = link_to "Show Review", post_review_path_helper(@treatment_review.review), target: :_blank
    %br/
    = link_to 'Edit Review', edit_review_path(@treatment_review.review), remote: true
  - else
    = link_to 'Add Review', new_review_path(treatment_id: treatment.id), class: 'btn btn-success treatment_review_link', remote: true

app/views/treatments/batch_create.js.haml
:plain
  $('#treatments_container').html('#{j render partial: 'personal_profiles/treatments'}');
  $('#tags-treatments').tagsinput('removeAll');
  $('.treatments-submit').text('Add').prop('disabled', false);
  init_treatments_select2();
  var errors = "#{@errors}";
  if (errors){
    $.bootstrapGrowl(errors, {
      type: 'error',
      offset: {from: 'top', amount: 80}
    });
  }
  $(".medical-treatments-table").trigger('update');
  $('body').trigger('init_treatment_toggles');

app/views/treatments/batch_delete.js.haml
:plain
  $('#treatments_container').html('#{j render partial: 'personal_profiles/treatments'}');
  $('body').trigger('init_treatment_toggles');
  init_treatments_select2();
  $('.scrollable-area').css({'height': ($(window).height() - 90) + 'px'})

app/views/treatments/create.js.haml
:plain
  $('#treatments_container').html('#{escape_javascript(render partial: 'personal_profiles/treatments')}')
  $('body').trigger('init_treatment_toggles');
  $('#treatment_treatment').val('')
  $('#treatment_condition_id').val('')
  load_period_listeners();
  load_review_button_listeners();

app/views/treatments/destroy.js.haml
:plain
  $('#treatments_container .treatment[data-treatment-id="#{@treatment_id}"]').remove();
  load_period_listeners();
  load_review_button_listeners();
  $(".medical-treatments-table").trigger('update');

app/views/treatments/edit.js.haml
:plain
  $("#{escape_javascript render('edit_name')}").appendTo('body').modal({show: true});

app/views/treatments/update.js.haml
:plain
  $("#edit-treatment-name-modal").on('hidden', function() {
    $(this).remove();
  }).modal('hide');
  $("tr.treatment[data-treatment-id='#{@treatment.id}']").replaceWith('#{j render(partial: 'treatments/treatment', object: @treatment)}')
  $('body').trigger('init_treatment_toggles');
  load_period_listeners();
  load_review_button_listeners();