config/routes.rb
Healclick::Application.routes.draw do

  get '/treatments/:treatment_summary_id', to: redirect('/treatments/%{treatment_summary_id}/reviews')
  get '/doctors/:doctor_summary_id', to: redirect('/doctors/%{doctor_summary_id}/reviews')

  Redirect.all.each do |redir|
    get redir.from, to: redirect(redir.to)
  end
  post 'questionnaire/save_categories'
  post 'questionnaire/next_question'
  mount_roboto
  get 'system_settings/create'
  get 'system_settings/update'
  put 'system_settings/points_save'
  get 'time_series_analysis', to: 'users#time_series_analysis'
  get 'time_series_analysis_admin', to: 'users#time_series_analysis_admin'
  get 'main', to: 'home#index', post_type: 'any', as: 'everything'
  get 'topics', to: 'home#index', post_type: 'all_topics'
  get 'medical-topics', to: 'home#index', post_type: 'medical_topics', as: 'medical_topics'
  get 'social-topics', to: 'home#index', post_type: 'social_topics', as: 'social_topics'
  get 'fun-stuff', to: 'home#index', post_type: 'fun_stuff', as: 'fun_stuff'
  get 'introductions', to: 'home#index', post_type: 'introductions'
  get 'faq', to: 'home#index', post_type: 'faq'
  get 'blog', to: 'home#index', post_type: 'blog'
  get 'conditions/autocomplete', to: 'conditions#autocomplete'
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  devise_for :users, path_names: {sign_in: 'login', sign_out: 'logout' }, controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations' }

  resources :posts do
    get :post_body, on: :member
    get :mark_as_helpful, on: :member
    get :follow, on: :member
    get :unfollow, on: :member
    get :luv, on: :member
    get :say_something, on: :collection
    get :expand_replies, on: :member
    resources :comments do
      resources :comments
      get :mark_as_helpful, on: :member
      get :luv, on: :member
    end
  end

  resources :noindex_rules, only: [:create, :destroy]

  resources :comments do
    get :mark_as_helpful, on: :member
    get :luv, on: :member
  end

  get '/reviews/summary', to: redirect('/treatments')
  resources :reviews do
    get :interest, on: :member
  end
  get '/treatments', to: 'reviews#summary', as: :summary_reviews

  resources :notifications do 
    get :read, on: :member
    get :mark_all_as_read, on: :collection
    delete :delete_all, on: :collection
  end

  resources :messages do 
    get :sent, on: :collection
    get :mark_all_as_read, on: :collection
    delete :delete_all, on: :collection
    delete :delete_all_sent, on: :collection
  end

  resources :users do 
    get :autocomplete, :on => :collection
    get :favorited_me, on: :member
    get :my_favorites, on: :member
    get :follow, on: :member
    get :unfollow, on: :member
    get :luv, on: :member
    get :leaderboard, on: :collection
    get :ranking, on: :collection
    get :favorite_list, on: :collection
    resources :photos do
      get :set_as_profile, on: :member    
      resources :comments
    end
    get :map, on: :collection
  end

  resources :photos do
    get :set_as_profile, on: :member
    resources :comments
  end

  resources :user_conditions

  resources :symptoms do 
    get :autocomplete, :on => :collection
    get :set_level, on: :member
    get :set_period, on: :member
    post :batch_create, on: :collection
    patch :batch_update, on: :collection
    post :popular_symptoms, on: :collection
    delete :batch_delete, on: :collection
  end

  resources :treatments do 
    get :autocomplete, :on => :collection
    get :set_level, on: :member
    get :set_period, on: :member
    put :set_type, on: :member
    resources :treatment_reviews
    post :batch_create, on: :collection
    patch :batch_update, on: :collection
    delete :batch_delete, on: :collection
  end

  resources :doctors do
    get :autocomplete, on: :collection
    post :batch_create, on: :collection
  end

  resources :treatment_reviews do
    get :autocomplete, :on => :collection
    get :check_unique_name, on: :collection
  end
  resources :doctor_reviews do
    # get :summary, on: :collection
    get :check_unique_name, on: :collection
  end


  get '/treatments/:treatment_summary_id/reviews/:id', to: 'posts#show', as: :treatment_summary_review
  get '/treatments/:treatment_summary_id/reviews', to: 'reviews#index', as: :treatment_summary_reviews
  get '/doctors/:doctor_summary_id/reviews/:id', to: 'posts#show', as: :doctor_summary_review_path
  get '/doctors/:doctor_summary_id/reviews', to: 'doctor_reviews#summary', as: :summary_doctor_reviews
  get '/treatment_summaries/:treatment_summary_id/reviews', to: 'reviews#old_routes', as: :old_routes

  resource :tracker, controller: :tracker do
    get :treatments, on: :collection
    get :symptoms, on: :collection
    get :well_being, on: :collection
  end

  get '/profile/:username', to: 'personal_profiles#show', as: :profile, constraints: {username: /.*/}

  get '/activity/:username', to: 'personal_profiles#activity', as: :activity, constraints: {username: /.*/}

  resource :personal_profile do
    get :select_main_condition, on: :member
    get :basic_info, on: :member
    get :my_health, on: :member
    get :profile_photo, on: :member
    get :symptoms, on: :member
    get :treatments, on: :member
    get :crop_photo, on: :member
    get :bookmarks, on: :member
    get :my_topics, on: :member
    get :symptoms_chart, on: :member
    patch :crop_photo, on: :member
  end

  resources :labs, only: [:update] do
    get :autocomplete, on: :collection
    get :change_date, on: :collection
    delete :batch_delete, on: :collection
    post :batch_create, on: :collection
  end

  resources :events, :only => [:update, :create, :show, :index]

  get 'settings', to: 'settings#index', as: :settings
  patch 'settings', to: 'settings#index', as: :post_settings

  post 'settings/set', to: 'settings#set', as: 'set_setting'

  resources :system_settings

  get 'home', to: 'home#new_home', as: :home
  get 'guest_sidebar', to: 'home#guest_sidebar'

  get 'skip_to_dashboard', to: 'home#skip', as: :skip_to_dashboard

  get 'my_click', to: 'my_click#index', as: :my_click
  get 'conditions/:condition_id', to: 'home#index', as: :conditions

  get 'landing', to: 'main#index', as: :landing
  get 'run_digest', to: 'main#run_digest'
  
  root to: 'home#new_home'

  # Error
  get '404', to: 'errors#index_404'
  get '500', to: 'errors#index_500'
end

RailsAdmin::Engine.routes.draw do
  get 'noindex_rules/destroy'
  get 'noindex_rules/create'
  get 'questionnaire/save_categories'
  get 'questionnaire/next_question'
  mount_roboto
  controller 'main' do
    scope ':model_name' do
      post 'bulk_edit_reviews', :to => :bulk_edit_reviews, :as => 'bulk_edit_reviews'
      post 'bulk_edit_treatments', :to => :bulk_edit_treatments, :as => 'bulk_edit_treatments'

      # Merge Treatment Summaries
      post 'bulk_edit_treatment_summaries', :to => :bulk_edit_treatment_summaries, :as => 'bulk_edit_treatment_summaries'
      get 'bulk_edit_treatment_summaries', :to => :get_bulk_edit_treatment_summaries, :as => 'get_bulk_edit_treatment_summaries'

      # Merge Symptoms Summaries
      post 'bulk_merge_symptom_summaries', :to => :bulk_merge_symptom_summaries, :as => 'bulk_merge_symptom_summaries'
      get 'bulk_merge_symptom_summaries', :to => :get_bulk_merge_symptom_summaries, :as => 'get_bulk_merge_symptom_summaries'
    end
  end
end

app/views/shared/_add_team.html.haml
.add-my-team{class: "add-team-#{user.id}"}
  - if current_user.following?(user)
    My Teammate
  - else
    = link_to 'Add To My Team', follow_user_path(user), remote: true, class: 'btn btn-default btn-xs'

app/views/shared/_analytics.html.haml
:javascript
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){ (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o), m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m) })(window,document,'script','//www.google-analytics.com/analytics.js','ga'); 
  ga('create', 'UA-41319207-1', 'healclick.com'); 
  ga('require', 'displayfeatures');
  if (getQueryVariable("utm_source")){
    ga('set', 'dimension5', getQueryVariable("utm_source"));
  }
- if current_user
  :javascript
    ga('set', 'dimension1', 'registereduser');
- if params[:action] == 'select_main_condition' && !current_user.finished_profile?
  :javascript
    ga('set', 'dimension2', 'newlyregistereduser');
    var today = new Date();
    var weekno = today.getWeek();
    ga('set', 'dimension3', weekno);
- if params[:action] == 'basic_info' && params[:commit] == 'Continue'
  :javascript
    ga('set', 'dimension4', '#{current_user.main_condition.try(:name)}');
- if params[:signed_in].present?
  :javascript
    ga('set', 'dimension6', '#{current_user.main_condition.try(:name)}');
:javascript
  ga('send', 'pageview');

app/views/shared/_clicky.html.haml
.clearfix.left.clicky
  %a{title: "Web Analytics", href:"http://clicky.com/100619836"}
    %img{alt:"Web Analytics", src:"//static.getclicky.com/media/links/badge.gif", border:"0"}
  = javascript_include_tag "//static.getclicky.com/js"
  :javascript
    try{ clicky.init(100619836); }catch(e){}
  %noscript
    %p
      %img{alt: "Clicky", width: "1", height: "1", src:"//in.getclicky.com/100619836ns.gif"}

app/views/shared/_doctor_review_form.html.haml
- @doctor_review ||= @doctor.doctor_review.nil? ? @doctor.build_doctor_review : @doctor.doctor_review

.modal.fade#doctor-review-modal.doctor_review_form.review_form_modal
  .modal-dialog
    .modal-content
      - @remote = false if params[:controller] == 'home'
      
      = form_for @doctor_review, class: "form-horizontal", remote: @remote do |f|
        .modal-header
          %button{:type => "button", :class => "close", :"data-dismiss" => "modal", :"aria-hidden" => "true"} &times;
          %h4.modal-title
            = @doctor_review.new_record? ? 'New' : 'Update'
            Review

        .modal-body
          = render 'shared/doctor_review_form_body', f: f

app/views/shared/_doctor_review_form_body.html.haml
#review_body
  .doctor_review_form
    - if @doctor.present?
      = hidden_field_tag :doctor_id, @doctor.id
    = f.fields_for :doctor do |ft|

      = ft.hidden_field :id

      - ft.object.user_id = current_user.id if ft.object.user_id.blank?
      = ft.hidden_field :user_id

      = ft.hidden_field :skip_review_update

      .row
        .col-lg-6.col-md-6.col-sm-6.col-xs-12.compensate
          .control-group
            = ft.label :doctor, class: "control-label"          
            .controls
              = ft.text_field :name, class: "typeahead doctor_name form-control", autocomplete: "off"
              %p.text-error.error-unique.hide You already entered this doctor. To add a review, go to #{link_to 'Doctors', my_health_personal_profile_path(medical_editor: :doctors) } and click the "Add Review" button

        .col-lg-6.col-md-6.col-sm-6.col-xs-12.compensate
          .control-group
            .controls            
              %label#currently-seeing
                = ft.check_box :currently_seeing, class: "input-medium change-currently_taking"
                Currently Seeing?

      .row          
        .col-lg-6.col-md-6.col-sm-6.col-xs-12.compensate
          .control-group
            = ft.label :started, class: "control-label"
            .controls.date_select
              = ft.date_select :started_on, {discard_day: true, order: [:month, :year], start_year: 1990, end_year: Time.now.year}, { class: 'form-control select2' }

        .col-lg-6.col-md-6.col-sm-6.col-xs-12.compensate
          .ended-period{style: "margin: 0px;", class: ('hide' if ft.object.currently_seeing?)}
            .control-group
              = ft.label :ended, class: "control-label"
              .controls.date_select
                = ft.date_select :ended_on, {discard_day: true, order: [:month, :year], start_year: 1990, end_year: Time.now.year}, { class: 'form-control select2' }

      .row        
        .col-lg-6.col-md-6.col-sm-6.col-xs-12.compensate          
          .control-group
            %p
              %label.control-label Recommended?
            = link_to 'Yes', 'javascript:void()', class: "centered label-default doctor-label label one-line #{"label-info" if @doctor.try(:recommended?)}", remote: true, method: :patch
            = link_to 'No', 'javascript:void()', class: "centered label-default doctor-label label one-line #{"label-info" if @doctor.try(:recommended) == false}", remote: true, method: :patch
            = ft.hidden_field :recommended

        .col-lg-6.col-md-6.col-sm-6.col-xs-12.compensate
          .control-group
            .controls
              = ft.label :location, class: "control-label"
              - selected = ft.object.country_id.nil? ? current_user.country_id : ft.object.country_id
              = ft.select :country_id, options_for_select([['Please Select', '']] + Country.order('name asc').map{|c| [c.name, c.id]}, selected), {}, class: 'form-control select2'
            
            .control-group.city-select{class: ('hide' if @doctor.try(:country_cache) == 'United States')}
              = ft.label :city, "City", class: "control-label"
              .controls
                = ft.text_field :city,  class: 'form-control', placeholder: 'Enter City'
            
            .control-group.states-select{class: ('hide' unless @doctor.try(:country_cache) == 'United States')}          
              = ft.label :state, "State", class: "control-label"
              .controls
                = ft.select :state, Country.us_states, {}, class: 'form-control select2'                  
    .col-lg-12.col-md-12.col-sm-12.col-xs-12.compensate
      .control-group
        = f.label :content, "Description", class: "control-label"
        .controls
          = f.text_area :content, placeholder: "Describe your experience", rows: 4, class: 'input form-control input-xxlarge users-typehead'
      
      .control-group.conditions_container{id: "add_conditions_container_#{@doctor_review.id}"}
        %label.control-label Conditions
        
        - if @doctor_review.conditions.present?
          - @doctor_review.conditions.each_with_index do |condition, index|
            .control-group.treatment_condition{id: "treatment_condition_container_#{condition.id}"}
              .controls
                = select_tag "doctor_review[condition_ids][]", options_for_select([['Select Condition', '']] + Condition.active.where("name is not null and name != ?", "").order('name asc').map{|c| [c.name, c.id]}, condition.id), class: "form-control"
                = link_to 'javascript:void(0);', class: 'remove_treatment_condition' do
                  %i.fa.fa-times-circle
        
        - if @doctor_review.new_record?
          .control-group.treatment_condition
            .controls
              = select_tag "doctor_review[condition_ids][]", options_for_select([['Select Condition', '']] + Condition.active.where("name is not null and name != ?", "").order('name asc').map{|c| [c.name, c.id]}, current_user.main_condition.try(:id)), class: " form-control"
              = link_to 'javascript:void(0);', class: 'remove_treatment_condition' do
                %i.fa.fa-times-circle
      
        .control-group
          .controls
            = link_to 'Add Condition', 'javascript:void(0);', class: 'add_condition_link', id: "add_conditions_link_#{@doctor_review.id}"

  .clearfix

.modal-footer
  = f.submit 'Save', class: 'btn btn-success', data: {disable_with: 'Saving...'}
  %button.btn.btn-default{:type => "button", :"data-dismiss" => "modal", :"aria-hidden" => "true"} Close

app/views/shared/_head.html.haml
- title, desc = MetaTag.display(params, request.fullpath)
= meta_tag(title, desc)

%title
  - if content_for?(:title)
    = yield :title or SystemSetting.get_value("page_description")  
  - else
    HealClick
    
- if content_for?(:meta_description)
  %meta{content: (yield :meta_description), name: "description"}/
- else
  %meta{content: SystemSetting.get_value("page_description"), name: "description"}/
  
- if content_for?(:meta_keyword)
  %meta{content: (yield :meta_keyword), name: "keyword"}/

%meta{:content => "width=device-width, initial-scale=1, maximum-scale=1", :name => "viewport"}/
%link{:rel => "icon", :href => "//s3-us-west-2.amazonaws.com/healclick-production-oregon/system/static/favicon.ico", :type => "image/x-icon"}/

app/views/shared/_landing_video_form.html.haml
.row.player
  .col-lg-8.col-md-8.col-sm-12.col-xs-12.visible-lg.visible-md
    %iframe.img-responsive{src: "//player.vimeo.com/video/80001271?byline=0&amp;portrait=0", width:"567", height:"320", frameborder: "0", webkitallowfullscreen: "webkitallowfullscreen", mozallowfullscreen: "mozallowfullscreen",  allowfullscreen: "allowfullscreen", class: ""}

  .col-lg-4.col-md-4.col-sm-12.col-xs-12
    .text-center.font-40.color-blue Sign Up

    = form_for(@resource, :as => 'user', :url => registration_url('user', protocol: authentication_protocol)) do |f|
      = devise_error_messages!

      .form-group
        = f.text_field :username, placeholder: "Username", class: 'form-control', required: true

      .form-group
        = f.email_field :email, :autofocus => true, placeholder: "Email", class: 'form-control', required: true

      .form-group
        = f.password_field :password, placeholder: "Password", class: 'form-control', required: true

      .form-group
        = f.password_field :password_confirmation, placeholder: "Password Confirmation", class: 'form-control', required: true

      .form-group
        %label
          = f.check_box :patient_or_caregiver, required: true
          I'm a patient or caregiver

      .form-group
        By clicking Sign Up, you agree to our
        = link_to 'http://healclick.freshdesk.com/solution/categories/113952/folders/263095/articles/176736-term-of-use', target: :_blank do
          Terms of Use
        %br/
        and that you have read our
        = succeed '.' do
          = link_to 'Privacy Policy', 'http://healclick.freshdesk.com/solution/categories/113952/folders/263095/articles/176732-privacy-policy', target: :_blank

      .form-group
        - @resource.build_referral
        = f.fields_for :referral do |rf|
          = rf.hidden_field :link, value: session['referrer']
        = f.submit "Sign Up", class: 'btn btn-success btn-block'


  .col-lg-8.col-md-8.col-sm-12.col-xs-12.visible-xs
    %iframe.img-responsive{src: "//player.vimeo.com/video/80001271?byline=0&amp;portrait=0", width:"567", height:"320", frameborder: "0", webkitallowfullscreen: "webkitallowfullscreen", mozallowfullscreen: "mozallowfullscreen",  allowfullscreen: "allowfullscreen", class: ""}

app/views/shared/_notifications.html.haml
.notifications-widget
  - cache current_user do
    .header      
      = link_to mark_all_as_read_notifications_path, remote: true, 'data-disable-with' => 'Loading...', class: "pull-left" do
        Mark All As Read
      
      = link_to notifications_path, class: "pull-right" do
        View All Notifications

      .clearfix
    
    #latest_notifications_container    
      - current_user.received_notifications.recent.page(1).per(5).each do |notification|
        = link_to notification_path(notification), remote: true do
          .top_notification{style: "#{notification.read? ? "" : "font-weight: bold;"}"}          
            
            .col-lg-2.col-md-3.col-sm-3.col-xs-3
              - if ['LUV_REPLY', 'LUV_POST', 'LUV_COMMENT', 'HELPFUL_COMMENT', 'HELPFUL_REPLY', 'HELPFUL_DISCUSSION', 'HELPFUL_DISCUSSION'].include?(notification.notification_type)
                = user_rounded_avatar(notification.from_user, size: "50x50", anonymous: false)
              - else
                - if notification.unscoped_comment.present?
                  = user_rounded_avatar(notification.from_user, size: "50x50", anonymous: notification.unscoped_comment.anonymous)
                - else
                  = user_rounded_avatar(notification.from_user, size: "50x50", anonymous: notification.notifiable.respond_to?(:anonymous) && notification.notifiable.anonymous)          
              .clearfix
            .col-lg-10.col-md-9.col-sm-9.col-xs-9
              .pull-right.timestamp
                = time_ago_in_words(notification.created_at) + " ago"

              - if %w(LUV_REPLY LUV_POST LUV_COMMENT HELPFUL_COMMENT HELPFUL_REPLY HELPFUL_DISCUSSION HELPFUL_DISCUSSION).include?(notification.notification_type)
                = notification.from_user.try(:username)# || "Anonymous"
              - else
                - if notification.unscoped_comment.present?
                  = notification.unscoped_comment.anonymous ? "Anonymous" : notification.from_user.try(:username) || "Anonymous"
                - else
                  = (notification.notifiable.respond_to?(:anonymous) && notification.notifiable.anonymous) ? "Anonymous" : notification.from_user.try(:username) || "Anonymous"                  
            
              .clearfix
                %div
                  - if notification.target_url.blank? || !notification.notifiable.present?
                    This has been deleted
                  - else
                    = notification_content(notification, 100, false)
            .clearfix
          .clearfix
    .clearfix

app/views/shared/_post_author.html.haml
- no_username ||= false
- no_score ||= false
- object.user = object.favorite_user if object.respond_to?(:favorite_user) && !object.favorite_user_id.nil?

.post-left{id: "author_#{object.user.id}"}
  - if object.respond_to?(:anonymous) && object.anonymous
    - unless no_username
      %h4.blue= current_user ? 'Anonymous' : 'Private'
    #{user_avatar(User.new, size: size, class: 'img-responsive')}

  - else
    - if current_user || (object.is_a?(Post) && object.faq_or_blog?)
      = link_to user_path(object.user), class: 'profile-popup-link' do
        - unless no_username
          %h4= truncate(object.user.username, length: 15) || truncate(object.user.full_name, length: 15)
        = user_avatar(object.user, size: size, class: 'img-responsive')
    
    - else
      %h4.black Private
      = user_avatar(nil, size: size, class: 'img-responsive')

    - if current_user && !no_score && current_user != object.user
      = render partial: 'shared/add_team', locals: {user: object.user}
      .clearfix

app/views/shared/_post_form.html.haml
.modal.fade#new_post_container
  .modal-dialog
    .modal-content
      .hidden.post-conditions-template
        .form-group.post_condition
          .controls
            = select_tag 'post[condition_ids][]', conditions_options_for_post(current_user.main_condition_id), class: 'condition_ids form-control'
            = link_to 'javascript:void(0);', class: 'remove_post_condition' do
              %span.symptoms-remove-icon

      = form_for post, remote: @remote do |f|
        .modal-header
          %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} &times;
          %h3.color-blue
            - if @post.new_record?
              What are your thoughts?
            - else
              Edit Post

        .modal-body
          .control-group
            = f.label :title, class: "control-label"
            .controls.modal-resp
              = f.text_field :title, placeholder: "Enter a Topic...", class: 'input-xxlarge form-control'

          .control-group
            = f.label :content, class: "control-label"
            .controls.modal-resp
              = f.text_area :content, rows: 7, class: "input-xxlarge users-typehead form-control", placeholder: "Enter a Post..."
      
          .control-group
            .controls
              .row
                .col-lg-6.col-md-6.col-sm-6.col-xs-6
                  = f.file_field :picture, class: "file-inputs btn btn-default", title: "Add a Picture"


                .col-lg-6.col-md-6.col-sm-6.col-xs-6
                  %label.checkbox
                    = f.check_box :anonymous
                    Post Anonymously
          
          .control-group
            = f.label :post_category_id, class: "control-label"
            .controls
              = f.select :post_category_id, post_categories_options, {}, class: " form-control"


          .conditions_container{id: "add_post_conditions_container_#{@post.id}"}
            %label.control-label Conditions
            - if @post.conditions.present?
              - if @post.all_conditions?
                .form-group.post_condition
                  .controls
                    = select_tag "post[condition_ids][]", conditions_options_for_post('all_conditions'), class: 'condition_ids form-control'
              - else
                - @post.conditions.each do |condition|
                  .form-group.post_condition{id: "post_condition_container_#{condition.id}"}
                    .controls
                      = select_tag "post[condition_ids][]", conditions_options_for_post(condition), class: 'condition_ids form-control'
                      = link_to 'javascript:void(0);', class: 'remove_post_condition', id: "post_condition_link_#{condition.id}" do
                        %span.symptoms-remove-icon
            - if post.new_record?
              .form-group.post_condition
                .controls
                  = select_tag "post[condition_ids][]", conditions_options_for_post(@post.conditions.present? ? nil : current_user.main_condition_id), class: 'condition_ids form-control'
            
            .control-group
              .controls.label-anon-resp
                = link_to 'Add Condition', 'javascript:void(0);', class: 'add_post_condition_link', id: "add_post_conditions_link_#{@post.id}"

        .modal-footer
          %button.btn.btn-default{:type => "button", :"data-dismiss" => "modal", :"aria-hidden" => "true"} Close
          = f.submit 'Post', :class => 'btn btn-success', 'data-disable-with' => 'Posting...'
          .hide#default-conditions
            = conditions_options_for_post

    = content_for :scripts do
      :javascript
        $('#post_post_category_id').trigger('change');

app/views/shared/_review_form.html.haml
- id ||= :review_form
- @treatment_review ||= @treatment.treatment_review.nil? ? @treatment.build_treatment_review : @treatment.treatment_review

.modal.fade.review_form_modal{id: id}
  .modal-dialog
    .modal-content
      = form_for @treatment_review, class: "form-horizontal", remote: @remote do |f|
        = hidden_field_tag :date, params[:date]
        .modal-header
          %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} &times;
          %h3
            = @treatment_review.new_record? ? 'New' : 'Update'
            Review
      
        .modal-body
          = render 'shared/review_form_body', f: f

app/views/shared/_support.html.haml
= javascript_include_tag "//healclick.freshdesk.com/widget/freshwidget.js"
:css
  @import url(//healclick.freshdesk.com/widget/freshwidget.css);
:javascript
  FreshWidget.init("", {"queryString": "&submitThanks=Thanks+for+your+feedback!++Someone+on+our+team+will+get+back+to+you+shortly.", "buttonText": "Support", "buttonColor": "black", "buttonBg": "#FFFCFD", "alignment": "3", "offset": "10px", "url": "//healclick.freshdesk.com", "assetUrl": "//healclick.freshdesk.com/widget"} );

app/views/shared/_tabbed_review_form.html.haml
- id ||= :tabbed_review_form
- @treatment_review ||= @treatment.treatment_review.nil? ? @treatment.build_treatment_review : @treatment.treatment_review

.modal.review_form_modal.tabbed-form-modal.fade{:id => id}
  .modal-dialog
    .modal-content
      .modal-header.no-border-bottom
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} &times;
        %ul.nav.nav-tabs
          %span.font-22.pull-left
            New Review For
            &nbsp&nbsp&nbsp&nbsp

          %li.active

            = link_to "#treatment_review_form_container", 'data-toggle' => :tab do
              Treatment

          %li
            = link_to "#doctor_review_form_container", 'data-toggle' => :tab do
              Doctor
      
      .modal-body     
        .tab-content
          .tab-pane.active#treatment_review_form_container
            = form_for @treatment_review, class: "form-horizontal", remote: @remote do |f|
              = render 'shared/review_form_body', f: f

          .tab-pane#doctor_review_form_container
            = form_for @doctor_review, class: "form-horizontal", remote: @remote do |f|
              = render 'shared/doctor_review_form_body', f: f