config/routes.rb
Healclick::Application.routes.draw do

  get '/treatments/:treatment_summary_id', to: redirect('/treatments/%{treatment_summary_id}/reviews')
  get '/doctors/:doctor_summary_id', to: redirect('/doctors/%{doctor_summary_id}/reviews')

  Redirect.all.each do |redir|
    get redir.from, to: redirect(redir.to)
  end
  post 'questionnaire/save_categories'
  post 'questionnaire/next_question'
  mount_roboto
  get 'system_settings/create'
  get 'system_settings/update'
  put 'system_settings/points_save'
  get 'time_series_analysis', to: 'users#time_series_analysis'
  get 'time_series_analysis_admin', to: 'users#time_series_analysis_admin'
  get 'main', to: 'home#index', post_type: 'any', as: 'everything'
  get 'topics', to: 'home#index', post_type: 'all_topics'
  get 'medical-topics', to: 'home#index', post_type: 'medical_topics', as: 'medical_topics'
  get 'social-topics', to: 'home#index', post_type: 'social_topics', as: 'social_topics'
  get 'fun-stuff', to: 'home#index', post_type: 'fun_stuff', as: 'fun_stuff'
  get 'introductions', to: 'home#index', post_type: 'introductions'
  get 'faq', to: 'home#index', post_type: 'faq'
  get 'blog', to: 'home#index', post_type: 'blog'
  get 'conditions/autocomplete', to: 'conditions#autocomplete'
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  devise_for :users, path_names: {sign_in: 'login', sign_out: 'logout' }, controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations' }

  resources :posts do
    get :post_body, on: :member
    get :mark_as_helpful, on: :member
    get :follow, on: :member
    get :unfollow, on: :member
    get :luv, on: :member
    get :say_something, on: :collection
    get :expand_replies, on: :member
    resources :comments do
      resources :comments
      get :mark_as_helpful, on: :member
      get :luv, on: :member
    end
  end

  resources :noindex_rules, only: [:create, :destroy]

  resources :comments do
    get :mark_as_helpful, on: :member
    get :luv, on: :member
  end

  get '/reviews/summary', to: redirect('/treatments')
  resources :reviews do
    get :interest, on: :member
  end
  get '/treatments', to: 'reviews#summary', as: :summary_reviews

  resources :notifications do 
    get :read, on: :member
    get :mark_all_as_read, on: :collection
    delete :delete_all, on: :collection
  end

  resources :messages do 
    get :sent, on: :collection
    get :mark_all_as_read, on: :collection
    delete :delete_all, on: :collection
    delete :delete_all_sent, on: :collection
  end

  resources :users do 
    get :autocomplete, :on => :collection
    get :favorited_me, on: :member
    get :my_favorites, on: :member
    get :follow, on: :member
    get :unfollow, on: :member
    get :luv, on: :member
    get :leaderboard, on: :collection
    get :ranking, on: :collection
    get :favorite_list, on: :collection
    resources :photos do
      get :set_as_profile, on: :member    
      resources :comments
    end
    get :map, on: :collection
  end

  resources :photos do
    get :set_as_profile, on: :member
    resources :comments
  end

  resources :user_conditions

  resources :symptoms do 
    get :autocomplete, :on => :collection
    get :set_level, on: :member
    get :set_period, on: :member
    post :batch_create, on: :collection
    patch :batch_update, on: :collection
    post :popular_symptoms, on: :collection
    delete :batch_delete, on: :collection
  end

  resources :treatments do 
    get :autocomplete, :on => :collection
    get :set_level, on: :member
    get :set_period, on: :member
    put :set_type, on: :member
    resources :treatment_reviews
    post :batch_create, on: :collection
    patch :batch_update, on: :collection
    delete :batch_delete, on: :collection
  end

  resources :doctors do
    get :autocomplete, on: :collection
    post :batch_create, on: :collection
  end

  resources :treatment_reviews do
    get :autocomplete, :on => :collection
    get :check_unique_name, on: :collection
  end
  resources :doctor_reviews do
    # get :summary, on: :collection
    get :check_unique_name, on: :collection
  end


  get '/treatments/:treatment_summary_id/reviews/:id', to: 'posts#show', as: :treatment_summary_review
  get '/treatments/:treatment_summary_id/reviews', to: 'reviews#index', as: :treatment_summary_reviews
  get '/doctors/:doctor_summary_id/reviews/:id', to: 'posts#show', as: :doctor_summary_review_path
  get '/doctors/:doctor_summary_id/reviews', to: 'doctor_reviews#summary', as: :summary_doctor_reviews
  get '/treatment_summaries/:treatment_summary_id/reviews', to: 'reviews#old_routes', as: :old_routes

  resource :tracker, controller: :tracker do
    get :treatments, on: :collection
    get :symptoms, on: :collection
    get :well_being, on: :collection
  end

  get '/profile/:username', to: 'personal_profiles#show', as: :profile, constraints: {username: /.*/}

  get '/activity/:username', to: 'personal_profiles#activity', as: :activity, constraints: {username: /.*/}

  resource :personal_profile do
    get :select_main_condition, on: :member
    get :basic_info, on: :member
    get :my_health, on: :member
    get :profile_photo, on: :member
    get :symptoms, on: :member
    get :treatments, on: :member
    get :crop_photo, on: :member
    get :bookmarks, on: :member
    get :my_topics, on: :member
    get :symptoms_chart, on: :member
    patch :crop_photo, on: :member
  end

  resources :labs, only: [:update] do
    get :autocomplete, on: :collection
    get :change_date, on: :collection
    delete :batch_delete, on: :collection
    post :batch_create, on: :collection
  end

  resources :events, :only => [:update, :create, :show, :index]

  get 'settings', to: 'settings#index', as: :settings
  patch 'settings', to: 'settings#index', as: :post_settings

  post 'settings/set', to: 'settings#set', as: 'set_setting'

  resources :system_settings

  get 'home', to: 'home#new_home', as: :home
  get 'guest_sidebar', to: 'home#guest_sidebar'

  get 'skip_to_dashboard', to: 'home#skip', as: :skip_to_dashboard

  get 'my_click', to: 'my_click#index', as: :my_click
  get 'conditions/:condition_id', to: 'home#index', as: :conditions

  get 'landing', to: 'main#index', as: :landing
  get 'run_digest', to: 'main#run_digest'
  
  root to: 'home#new_home'

  # Error
  get '404', to: 'errors#index_404'
  get '500', to: 'errors#index_500'
end

RailsAdmin::Engine.routes.draw do
  get 'noindex_rules/destroy'
  get 'noindex_rules/create'
  get 'questionnaire/save_categories'
  get 'questionnaire/next_question'
  mount_roboto
  controller 'main' do
    scope ':model_name' do
      post 'bulk_edit_reviews', :to => :bulk_edit_reviews, :as => 'bulk_edit_reviews'
      post 'bulk_edit_treatments', :to => :bulk_edit_treatments, :as => 'bulk_edit_treatments'

      # Merge Treatment Summaries
      post 'bulk_edit_treatment_summaries', :to => :bulk_edit_treatment_summaries, :as => 'bulk_edit_treatment_summaries'
      get 'bulk_edit_treatment_summaries', :to => :get_bulk_edit_treatment_summaries, :as => 'get_bulk_edit_treatment_summaries'

      # Merge Symptoms Summaries
      post 'bulk_merge_symptom_summaries', :to => :bulk_merge_symptom_summaries, :as => 'bulk_merge_symptom_summaries'
      get 'bulk_merge_symptom_summaries', :to => :get_bulk_merge_symptom_summaries, :as => 'get_bulk_merge_symptom_summaries'
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :check_profile, only: [:index, :new_home]
  before_filter :handle_condition
  before_filter :assign_variables
  skip_before_filter :authenticate_user!, :check_profile, only: [:skip]

  def skip
    current_user.finished_profile = true
    current_user.save
    redirect_to home_path
  end

  def index
    # Denied access for fun_stuf/introductions/social_posts for guests and /home?condition_id=my_conditions
    redirect_to landing_path, alert: 'You must be logged in to do that' if (current_user.nil? && %w(social_topics introductions).include?(params[:post_type])) || (params[:condition_id] == "my_conditions" && current_user.nil?)

    params[:sort_by] ||= 'posts.last_interaction_at desc'
    params[:post_type] ||= 'everything'

    params[:view] ||= session[:home_feed_view_mode]
    params[:view] ||= 'full'
    session[:home_feed_view_mode] = params[:view]

    @view = params[:view]

    social_category_ids = [PostCategory.find_by_name('Social Support').try(:id)]

    sort_key = params[:sort_by].gsub(/(\sdesc+)|(posts\.)/, '')

    @posts = Post.all

    unless params[:query].blank?
      ids = Post.text_search(query: params[:query]).results.map(&:id)
      @posts = @posts.with_ids(ids)
    end

    # Apply privacy settings
    unless current_user
      @posts = @posts.joins(:user).where('users.privacy = 1 or (users.privacy = 2 and posts.type = ?)', "Review")
      @posts = @posts.where('post_category_id is null OR post_category_id NOT IN (?)', social_category_ids + [PostCategory.find_by_name('Introductions').try(:id)])
    end
    @posts = @posts.for_feed.order(params[:sort_by])
    @posts = @posts.with_user_matching(current_user) if params[:sort_by] =~ /score/
    @posts = @posts.by_category(params[:post_category_id]) if params[:post_category_id].present?
    @posts = @posts.with_user_condition if params[:sort_by] =~ /conditions/
    @posts = @posts.group('posts.id')

    if @condition_id.present?
      if params[:post_type].present?
        any_conditions = @condition_id == 'any'
        case params[:post_type]
          when 'everything', 'All', 'any'
            unless any_conditions
              @base = @posts
              @reviews = @base.by_treatment_condition(@condition_id, current_user)
              @doctor_reviews = @base.by_doctor_condition(@condition_id, current_user)
              @posts = @base.by_conditions(@condition_id, current_user)
              @posts = @reviews + @posts + @doctor_reviews
            end
            @posts
          when 'social_topics'
            @posts = @posts.by_conditions(@condition_id, current_user) unless any_conditions
            @posts = @posts.by_category(social_category_ids)
          when 'fun_stuff'
            @posts = @posts.by_conditions(@condition_id, current_user) unless any_conditions
            @posts = @posts.by_category([PostCategory.find_by_name('Fun Stuff').try(:id)])
            unless current_user
              @posts = @posts.where('users.privacy = 1 or users.privacy = 2')
              @posts = @posts.by_category([PostCategory.find_by_name('Fun Stuff').try(:id)]).order(params[:sort_by])
            end
          when 'introductions'
            @posts = @posts.by_conditions(@condition_id, current_user) unless any_conditions
            @posts = @posts.by_category([PostCategory.find_by_name('Introductions').try(:id)])
          when 'faq'
            @posts = @posts.by_conditions(@condition_id, current_user) unless any_conditions
            @posts = @posts.by_category([PostCategory.find_by_name('FAQ').try(:id)])
          when 'blog'
            @posts = @posts.by_conditions(@condition_id, current_user) unless any_conditions
            @posts = @posts.by_category([PostCategory.find_by_name('Blog').try(:id)])
          when 'medical_topics'
            @posts = @posts.by_conditions(@condition_id, current_user) unless any_conditions
            @posts = @posts.by_category([PostCategory.find_by_name('Medical').try(:id)])
            unless current_user
              @posts = @posts.where('users.privacy = 1 or users.privacy = 2')
              @posts = @posts.by_category([PostCategory.find_by_name('Medical').try(:id)]).order(params[:sort_by])
            end
          when 'all_topics'
            @posts = @posts.by_conditions(@condition_id, current_user) unless any_conditions
            @posts = @posts.by_type('Post')
            unless current_user
              @posts = @posts.where('users.privacy = 1 or users.privacy = 2')
              @posts = @posts.order(params[:sort_by])
            end
          when 'treatment_reviews'
            @posts = @posts.by_type('Review')
            @posts = @posts.by_treatment_condition(@condition_id, current_user) unless any_conditions
          when 'doctor_reviews'
            @posts = @posts.by_type('Review').doctor_reviews
            @posts = @posts.by_doctor_condition(@condition_id, current_user) unless any_conditions
        end
      end
    end
    unless params[:desease_tag_search].blank?
      conditions = params[:desease_tag_search].split ','
      @base = @posts
      @posts = @posts.joins(:conditions).where('conditions.name IN (?)', conditions)
      @posts = @posts.having('COUNT(DISTINCT conditions_posts.condition_id) = ?', conditions.size) if conditions.size > 1
      @reviews = @base.joins(treatment_review: :conditions).where('conditions.name IN (?)', conditions).order(params[:sort_by])
      @reviews = @reviews.having('COUNT(DISTINCT conditions_treatment_reviews.condition_id) = ?', conditions.size) if conditions.size > 1
      @posts = @reviews + @posts
    end

    if @posts.kind_of?(Array)
      @posts.sort_by!{|u| u.send(sort_key).to_i}
      @posts.reverse!
      @posts = Kaminari.paginate_array(@posts).page(params[:page]).per(20)
    else
      @posts = @posts.page(params[:page]).per(20)
    end
  end

  def new_home
    return redirect_to everything_path(params) if params[:query].present?

    @topics = Post.all.for_feed.order('posts.last_interaction_at desc').group('posts.id')
    @condition_id = 'any' if !current_user && @condition_id == 'my_conditions'
    @topics = @topics.by_conditions(@condition_id, current_user) unless @condition_id == 'any'
    @topics = @topics.by_type('Post')
    unless current_user
      @topics = @topics.joins(:user).where('users.privacy = 1 or users.privacy = 2')
    end
    @topics = @topics.limit(5)

    if current_user
      posts_from_favorite = Post.all.not_anonymous
      posts_from_favorite = posts_from_favorite.followed_by(current_user).order('posts.created_at DESC')
      activity_logs = current_user.activity_logs.from_favorite_users

      my_posts = current_user.posts.not_tracking_updates.not_activity_reply
      if params[:filter].present?
        case params[:filter]
          when 'posts'
            posts_from_favorite = posts_from_favorite.not_tracking_updates
            activity_logs = activity_logs.by_type 'Comment'
          when 'photos'
            posts_from_favorite = []
            activity_logs = activity_logs.by_type('Photo').joins(:favorite_user)
            my_posts = []
          when 'tracking'
            my_posts =[]
            activity_logs = []
            posts_from_favorite = posts_from_favorite.tracking_updates
          else

        end
      else
        posts_from_favorite = posts_from_favorite.not_my(current_user.id)
      end

      @combined_records = (activity_logs + posts_from_favorite + my_posts).sort_by{|r| -r.created_at.to_i}

      if @combined_records.present?
        @combined_records = if @combined_records.respond_to?(:page)
          @combined_records.page(params[:page]).per(20)
        else
          Kaminari.paginate_array(@combined_records).page(params[:page]).per(20)
        end
      end
    end

    @active_users = User.last_online.limit(16)

    conditions = ''
    if @condition_id != 'any'
      return if !current_user && @condition_id == 'my_condiitons'
      conditions = @condition_id == 'my_conditions' ? [current_user.main_condition.try(:id)] + current_user.user_conditions.map(&:condition_id) : [Condition.find_by_slug(@condition_id).try(:id)]
      conditions.compact!
    end
    @condition_id = view_context.get_cached_condition_id == 'my_conditions' ? view_context.get_cached_condition_id : Condition.find_by_slug(view_context.get_cached_condition_id).try(:id)
    @condition_id = conditions.join(',') if view_context.get_cached_condition_id == 'my_conditions'
    @condition_id ||= 'any'
    query = "%#{params[:query]}%".downcase
    @summaries = TreatmentSummary.for_summary_page(@condition_id.to_s, params[:sort_by], query)
    @summaries = Kaminari.paginate_array(@summaries).page(params[:page]).per(5)
  end

  private

  def handle_condition
    @condition_id = params[:condition_id]
    if current_user
      @condition_id ||= current_user.settings.condition_id
    end
    @condition_id ||= cookies[:condition_id]

    if @condition_id.present? && !%w(any my_conditions).include?(@condition_id) && @condition_id.to_i.zero?
      @condition = Condition.find_by_slug(@condition_id)
      @condition_id = @condition.to_param
      if @condition.present?
        slug = @condition.slug
        cookies[:selected_community] = current_user.try(:main_condition).try(:name) == @condition.name ? 'main_condition' : @condition.name
      end
    end
    @condition_id ||= 'any'
    cookies[:selected_community] = 'all_conditions' if @condition_id == 'any'
    current_user.settings.condition_id = slug ? slug : @condition_id if current_user
    cookies[:condition_id] = slug ? slug : @condition_id
  end

  def assign_variables
    @post = current_user.posts.new if current_user
    @comment  = Comment.new
    @resource = User.new unless current_user
    @treatment_review = TreatmentReview.new
    @treatment_review.treatment = Treatment.new(period: "#{1.month.ago.strftime("%m-%Y")} - Current", user: current_user, skip_review_update: true)

app/helpers/home_helper.rb
module HomeHelper

  def feed_filter_options
    options = []
    options << ['All Updates', 'all', data: {url: url_for(params.merge(filter: 'all'))}]
    options << ['Posts Only', 'posts', data: {url: url_for(params.merge(filter: 'posts'))}]
    options << ['Photos Only', 'photos', data: {url: url_for(params.merge(filter: 'photos'))}]
    options << ['Tracking Updates Only', 'tracking', data: {url: url_for(params.merge(filter: 'tracking'))}]
  end
end

app/views/home/_fake_well_being.html.haml
.well-being-gradient
  - WellBeing::LEVELS.each do |level|
    .well-being-level
      %span{class: level}
        = render_svg level
.symptom-level
  .btn-group.btn-group-justified

    - Symptom::SCALE.each do |n|
      %a.btn{data: {level: n}, href: say_something_posts_path}
        %span.muted &bull;
        %span.rate= n

app/views/home/_talk_bar.html.haml
.col-xs-12.col-sm-4.col-md-4.col-lg-4
  .box-treatments
    .navbar-header
      %h1=link_to community_title_for_home('Topics'), topics_path(condition_id: params[:condition_id])
      %button.navbar-toggle{'data-target' => '.navbar-collapse-3', 'data-toggle' => 'collapse', type: 'button'}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
    .navbar-collapse.navbar-collapse-3.collapse
      %ul.list-treatments.list-talk
        - @topics.each do |post|
          %li
            %h6= link_to truncate(post.title, length: 25, omission: '...'), post_review_path_helper(post), class: 'color-green'
            = truncate(post.content, length: 80, omission: '...')
    .clearF

app/views/home/_title.html.haml
- if render_dropdown
  .row.community-filter
    .col-sm-5
      = select_tag 'community_filter', options_for_select(community_options, cookies[:selected_community]), class: 'full-width'

app/views/home/_tracker_bar.html.haml
.col-sm-4.col-md-4.col-lg-4
  .box-treatments.box-daily.health-tracker-item
    .navbar-header
      %h3= link_to 'Daily Health Tracker', my_health_personal_profile_path(medical_editor: :symptoms, anchor: :medical_tabs)
      %button.navbar-toggle{'data-target' => '.navbar-collapse-2', 'data-toggle' => 'collapse', type: 'button'}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
    .navbar-collapse.navbar-collapse-2.collapse
      - unless cookies[:hide_tracker_video].present?
        .how-it-works
          = link_to 'SEE HOW IT WORKS', '#', data: {toggle: 'modal', target: '#how-it-works-video'}
          %button.close.remove-tracker-help{type: 'button'}
            %span{'aria-hidden' => 'true'} ×
      %h3.overall-title{class: ('with-video' unless cookies[:hide_tracker_video].present?)} Overall, I'm feeling...
      .overall-rate
        - if current_user
          = form_for current_user, url: batch_update_symptoms_path, remote: true do |f|
            = render 'personal_profiles/well_being', form: f, blank: false
        - else
          = render 'fake_well_being'
      .tracker-controls
        - %w(symptoms treatments events labs_and_metrics doctors).each do |screen|
          - anchor = screen == 'labs_and_metrics' ? 'labs' : screen
          = link_to my_health_personal_profile_path(medical_editor: anchor, anchor: 'medical_tabs'), class: "col-sm-6 col-xs-6 icon-link #{screen}-link", 'data-screen' => screen do
            = image_tag "tracker/#{screen}.png", class: 'img-responsive margin-auto'
            = screen.humanize
        = link_to my_health_personal_profile_path(medical_editor: :visualize, anchor: 'medical_tabs'), class: 'col-sm-6 col-xs-6 icon-link health-graph-link' do
          = image_tag 'tracker/statistics.png', size: '57x57'
          %div Health Graph
  .modal.fade#how-it-works-video{role: 'dialog'}
    .modal-dialog
      .modal-content
        .modal-header
          %button.close{'data-dismiss' => 'modal', type: 'button'}
            %span{'aria-hidden' => 'true'} ×
            %span.sr-only Close
          %h4.modal-title How To Use Our Health Tracker
        .modal-body
          %iframe{allowfullscreen: '', frameborder: '0', height: '281', mozallowfullscreen: '', src: '//player.vimeo.com/video/100963945', webkitallowfullscreen: '', width: '100%'}

app/views/home/_treatments_bar.html.haml
.col-sm-4.col-md-4.col-lg-4
  .box-treatments
    .navbar-header
      %h1
        = link_to community_title_for_home('Treatments'), summary_reviews_path
      %button.navbar-toggle{"data-target" => ".navbar-collapse-1", "data-toggle" => "collapse", type: "button"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
    .navbar-collapse.collapse.navbar-collapse-1
      %ul.list-treatments.treatment-summary-container
        - @summaries.each do |summary|
          %li
            %h6
              = link_to summary.treatment_name, treatment_summary_reviews_path(summary), class: 'green'
            %span.rating
              %span.empty
                - 5.times do
                  = fa_icon 'star-o'
              %span.filled{style: "width: #{summary.average_level/5.00*93.00}px"}
                - 5.times do
                  = fa_icon 'star'

            = link_to "(See all #{pluralize(summary.post_count_by_condition(current_user), 'review')})", treatment_summary_reviews_path(summary), class: 'see-all'
      .clearF

app/views/home/index.html.haml
- @view ||= 'full'

.col-lg-12.col-md-12.col-sm-12.col-xs-12
  .bolder.search-count.pull-left
    = "Showing #{@posts.total_count} Results" if show_number_of_search_items?
    = render 'shared/page_category_select'

- unless show_number_of_search_items?
  .col-lg-3.col-md-6.col-sm-6.col-xs-6
    = select_tag 'sort_by', options_for_select([['Latest Activity', post_sorter_path('posts.last_interaction_at desc')], ['Newest', post_sorter_path('posts.created_at desc')],  ['Most Interactions', post_sorter_path('posts.interactions_count desc')], ['Most Helpful', post_sorter_path('posts.helpfuls_count desc')], ['Most Viewed', post_sorter_path('posts.views_count desc')]], "?#{URI.unescape request.query_string}"), class: 'pull-left select2-without-search'    

.col-lg-9.col-md-6.col-sm-6.col-xs-6
  .dropdown.pull-right
    .dropdown-toggle.hover-dropdown.hite{ data: {target: '#', hover: 'dropdown'} }          
      %h4.inline Format
      .glyphicon.glyphicon-chevron-down{style: "font-size: 15px;"}            
    %ul.dropdown-menu.switch-menu{:role => "menu", :"aria-labelledby" => "dLabel"}
      %li= link_to 'List View', params.merge(:view => 'list'), class: ( "active" if @view == "list" )        
      %li= link_to 'Feed View', params.merge(:view => 'full'), class: ( "active" if @view == "full" )

- if current_user
  #post_form_container
    = render partial: 'shared/post_form', locals: {post: @post}

.clearfix

#posts_container.scroll-pagination
  = render partial: 'posts/posts_batch'

.more_posts.centered{style: "margin: 20px;"}
  = hidden_field_tag :content_path, post_sorter_path(params[:sort_by]), id: :content_path

  .loading_container
    = image_tag 'loading.gif', size: "20x20"

- if current_user
  = render 'shared/tabbed_review_form'

#comment_form_container

#profile_popup

app/views/home/index.js.haml
:plain
  new_page = '#{j render(partial: "posts/posts_batch")}';
- if params[:page].present?
  :plain
    $('#posts_container').append(new_page);
- else
  :plain
    $('#posts_container').html(new_page);

- if params[:query].blank?
  :plain
    $('.sorting-container .right').show()
    $('.search-count').text('')
- else
  :plain
    $('#sort_by').parent().hide()
    $('.search-count').text('Showing #{@posts.total_count} Results')

:plain
  $('.loading_container').hide();
  load_useful_link_listeners();
  $('.file-inputs:not(.changed)').addClass('changed').bootstrapFileInput();

app/views/home/new_home.html.haml
- content_for :title do
  = title 'Home', :home
.row.home-row.margin-bottom-10
  .bottom-spacing.crow
    = render 'tracker_bar'
    = render 'treatments_bar'
    = render 'talk_bar'

  .col-sm-8.col-md-8.col-lg-8
    - if current_user
      .btn-spacing
        = link_to say_something_posts_path, class: 'btn btn-something btn-success', remote: !current_user.nil? do
          = image_tag 'comment.png', size: '20x20'
          Say Something
        = link_to '#', class: 'btn btn-treatment', id: 'tabbed_form_link' do
          = image_tag 'pill-xxl.png', size: '20x20'
          Share Treatment
      %h2.heading-my-team My Team's Recent Activity
      .feed-filter
        = select_tag :filter, options_for_select(feed_filter_options, params[:filter]), class: 'select2-without-search'
      .white-bg.scroll-pagination
        = render 'my_click/feed_batch'
        .loading_container
          = image_tag 'loading.gif', size: '20x20'
        - if @combined_records.blank?
          %center
            %p.lead
              You haven't added anyone to Your Team! Find similar patients by checking out our #{link_to 'Users', users_path}, #{link_to 'Topics', topics_path}, and #{link_to 'Treatment Reviews', summary_reviews_path}
              - if current_user.main_condition.present?
                from our #{link_to "#{current_user.main_condition.try(:name).try(:titleize)} community", conditions_path(current_user.main_condition.try(:slug))}
  - if current_user
    .col-sm-4.col-md-4.col-lg-4.hidden-xs
      = render 'questionnaire/questionnaire' if show_questionnaire?
      .box-treatments.box-recently
        %h3 Recently Active
        %ul.list-recentlyImages
          - @active_users.each do |user|
            %li
              = link_to user_avatar(user), user_path(user), class: 'pshow_questionnaire?a`rofile-popup-link'
        %p.text-copyright © HealClick All Rights Reserved.
    #post_form_container
      = render partial: 'shared/post_form', locals: {post: @post}
    = render 'shared/tabbed_review_form'

    #comment_form_container
-unless current_user
  = render 'shared/landing_video_form'
  .row
    .col-lg-12
      = image_tag 'healclick-about.jpg', class: 'img-responsive'

app/views/home/new_home.js.haml
:plain  
  new_page = '#{j render(partial: 'my_click/feed_batch')}';
- if params[:page].present?
  :plain
    $('#posts_container').append(new_page);
- else
  :plain
    $('#posts_container').html(new_page);
:plain
  $('.loading_container').hide();
  load_useful_link_listeners();
  $('.file-inputs:not(.changed)').addClass('changed').bootstrapFileInput();