config/routes.rb
Healclick::Application.routes.draw do

  get '/treatments/:treatment_summary_id', to: redirect('/treatments/%{treatment_summary_id}/reviews')
  get '/doctors/:doctor_summary_id', to: redirect('/doctors/%{doctor_summary_id}/reviews')

  Redirect.all.each do |redir|
    get redir.from, to: redirect(redir.to)
  end
  post 'questionnaire/save_categories'
  post 'questionnaire/next_question'
  mount_roboto
  get 'system_settings/create'
  get 'system_settings/update'
  put 'system_settings/points_save'
  get 'time_series_analysis', to: 'users#time_series_analysis'
  get 'time_series_analysis_admin', to: 'users#time_series_analysis_admin'
  get 'main', to: 'home#index', post_type: 'any', as: 'everything'
  get 'topics', to: 'home#index', post_type: 'all_topics'
  get 'medical-topics', to: 'home#index', post_type: 'medical_topics', as: 'medical_topics'
  get 'social-topics', to: 'home#index', post_type: 'social_topics', as: 'social_topics'
  get 'fun-stuff', to: 'home#index', post_type: 'fun_stuff', as: 'fun_stuff'
  get 'introductions', to: 'home#index', post_type: 'introductions'
  get 'faq', to: 'home#index', post_type: 'faq'
  get 'blog', to: 'home#index', post_type: 'blog'
  get 'conditions/autocomplete', to: 'conditions#autocomplete'
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  devise_for :users, path_names: {sign_in: 'login', sign_out: 'logout' }, controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations' }

  resources :posts do
    get :post_body, on: :member
    get :mark_as_helpful, on: :member
    get :follow, on: :member
    get :unfollow, on: :member
    get :luv, on: :member
    get :say_something, on: :collection
    get :expand_replies, on: :member
    resources :comments do
      resources :comments
      get :mark_as_helpful, on: :member
      get :luv, on: :member
    end
  end

  resources :noindex_rules, only: [:create, :destroy]

  resources :comments do
    get :mark_as_helpful, on: :member
    get :luv, on: :member
  end

  get '/reviews/summary', to: redirect('/treatments')
  resources :reviews do
    get :interest, on: :member
  end
  get '/treatments', to: 'reviews#summary', as: :summary_reviews

  resources :notifications do 
    get :read, on: :member
    get :mark_all_as_read, on: :collection
    delete :delete_all, on: :collection
  end

  resources :messages do 
    get :sent, on: :collection
    get :mark_all_as_read, on: :collection
    delete :delete_all, on: :collection
    delete :delete_all_sent, on: :collection
  end

  resources :users do 
    get :autocomplete, :on => :collection
    get :favorited_me, on: :member
    get :my_favorites, on: :member
    get :follow, on: :member
    get :unfollow, on: :member
    get :luv, on: :member
    get :leaderboard, on: :collection
    get :ranking, on: :collection
    get :favorite_list, on: :collection
    resources :photos do
      get :set_as_profile, on: :member    
      resources :comments
    end
    get :map, on: :collection
  end

  resources :photos do
    get :set_as_profile, on: :member
    resources :comments
  end

  resources :user_conditions

  resources :symptoms do 
    get :autocomplete, :on => :collection
    get :set_level, on: :member
    get :set_period, on: :member
    post :batch_create, on: :collection
    patch :batch_update, on: :collection
    post :popular_symptoms, on: :collection
    delete :batch_delete, on: :collection
  end

  resources :treatments do 
    get :autocomplete, :on => :collection
    get :set_level, on: :member
    get :set_period, on: :member
    put :set_type, on: :member
    resources :treatment_reviews
    post :batch_create, on: :collection
    patch :batch_update, on: :collection
    delete :batch_delete, on: :collection
  end

  resources :doctors do
    get :autocomplete, on: :collection
    post :batch_create, on: :collection
  end

  resources :treatment_reviews do
    get :autocomplete, :on => :collection
    get :check_unique_name, on: :collection
  end
  resources :doctor_reviews do
    # get :summary, on: :collection
    get :check_unique_name, on: :collection
  end


  get '/treatments/:treatment_summary_id/reviews/:id', to: 'posts#show', as: :treatment_summary_review
  get '/treatments/:treatment_summary_id/reviews', to: 'reviews#index', as: :treatment_summary_reviews
  get '/doctors/:doctor_summary_id/reviews/:id', to: 'posts#show', as: :doctor_summary_review_path
  get '/doctors/:doctor_summary_id/reviews', to: 'doctor_reviews#summary', as: :summary_doctor_reviews
  get '/treatment_summaries/:treatment_summary_id/reviews', to: 'reviews#old_routes', as: :old_routes

  resource :tracker, controller: :tracker do
    get :treatments, on: :collection
    get :symptoms, on: :collection
    get :well_being, on: :collection
  end

  get '/profile/:username', to: 'personal_profiles#show', as: :profile, constraints: {username: /.*/}

  get '/activity/:username', to: 'personal_profiles#activity', as: :activity, constraints: {username: /.*/}

  resource :personal_profile do
    get :select_main_condition, on: :member
    get :basic_info, on: :member
    get :my_health, on: :member
    get :profile_photo, on: :member
    get :symptoms, on: :member
    get :treatments, on: :member
    get :crop_photo, on: :member
    get :bookmarks, on: :member
    get :my_topics, on: :member
    get :symptoms_chart, on: :member
    patch :crop_photo, on: :member
  end

  resources :labs, only: [:update] do
    get :autocomplete, on: :collection
    get :change_date, on: :collection
    delete :batch_delete, on: :collection
    post :batch_create, on: :collection
  end

  resources :events, :only => [:update, :create, :show, :index]

  get 'settings', to: 'settings#index', as: :settings
  patch 'settings', to: 'settings#index', as: :post_settings

  post 'settings/set', to: 'settings#set', as: 'set_setting'

  resources :system_settings

  get 'home', to: 'home#new_home', as: :home
  get 'guest_sidebar', to: 'home#guest_sidebar'

  get 'skip_to_dashboard', to: 'home#skip', as: :skip_to_dashboard

  get 'my_click', to: 'my_click#index', as: :my_click
  get 'conditions/:condition_id', to: 'home#index', as: :conditions

  get 'landing', to: 'main#index', as: :landing
  get 'run_digest', to: 'main#run_digest'
  
  root to: 'home#new_home'

  # Error
  get '404', to: 'errors#index_404'
  get '500', to: 'errors#index_500'
end

RailsAdmin::Engine.routes.draw do
  get 'noindex_rules/destroy'
  get 'noindex_rules/create'
  get 'questionnaire/save_categories'
  get 'questionnaire/next_question'
  mount_roboto
  controller 'main' do
    scope ':model_name' do
      post 'bulk_edit_reviews', :to => :bulk_edit_reviews, :as => 'bulk_edit_reviews'
      post 'bulk_edit_treatments', :to => :bulk_edit_treatments, :as => 'bulk_edit_treatments'

      # Merge Treatment Summaries
      post 'bulk_edit_treatment_summaries', :to => :bulk_edit_treatment_summaries, :as => 'bulk_edit_treatment_summaries'
      get 'bulk_edit_treatment_summaries', :to => :get_bulk_edit_treatment_summaries, :as => 'get_bulk_edit_treatment_summaries'

      # Merge Symptoms Summaries
      post 'bulk_merge_symptom_summaries', :to => :bulk_merge_symptom_summaries, :as => 'bulk_merge_symptom_summaries'
      get 'bulk_merge_symptom_summaries', :to => :get_bulk_merge_symptom_summaries, :as => 'get_bulk_merge_symptom_summaries'
    end
  end
end

app/controllers/personal_profiles_controller.rb
class PersonalProfilesController < ApplicationController
  skip_before_filter :authenticate_user!, :check_profile, only: [:select_main_condition, :update, :basic_info, :my_health, :profile_photo, :check_main_condition]

  before_filter :redirect_to_landing, only: [:show, :my_health, :basic_info, :profile_photo]
  before_filter :set_finished_profile

  def show
    @user = User.find_by_username(params[:username])
    return redirect_to home_path if @user.blank?
    @message = Message.new(to_user_id: @user.id)
  end

  def symptoms_chart
    @user = User.find_by_id(params[:id])
    max_lab_value = @user.labs.find_max_current_value(@user)
    max_lab_value = 1 unless max_lab_value
    @symptoms_chart = LazyHighCharts::HighChart.new('HighStock') do |f|
      if params[:treatments]
        f.yAxis [{
          min: 0,
          max: 10,
          top: 0,
          height: 200,
          lineColor: 'transparent',
          gridLineWidth: 0,
          gridLineColor: 'transparent',
          labels: {enabled: false},
          title: {text: 'Treatments', style: {color: 'transparent'}},
        }, {
          min: 0, max: 10, top: 200, maxPadding: 0.5, height: 200, showLastLabel: true,
            labels: {formatter: 'function() {
                        var labels = {0: "None", 10: "Worst"};
                        label = labels[this.value] ? labels[this.value] : this.value
                        return label;
                      }'.js_code
            }
        }, {min: 0, max: max_lab_value, top: 450, height: 150, showFirstLabel: true, showLastLabel: true, labels: {formatter: 'function(){return this.value;}'.js_code}}]
        f.navigator margin: 100
        f.xAxis top: 130
      else
        f.yAxis min: 0, max: 10
      end
      @user.symptoms.find_each do |symptom|
        next if symptom.nil?
        data = symptom.symptom_logs.order('date ASC')
          .map {|v| [v.date.to_time.to_i * 1000, v.numeric_level]}
          .reject {|v| v.last.blank?}
        next if data.blank?
        series_params = {name: symptom.symptom, type: :spline, data: data, marker: {enabled: true, radius: 3}, shadow: true}
        series_params.merge!(yAxis: 1) if params[:treatments]
        f.series series_params
      end
      @user.well_being.tap do |well_being|
        next if well_being.blank?
        data = well_being.well_being_logs.order('date ASC')
          .map {|v| [v.date.to_time.to_i * 1000, v.numeric_level]}
          .reject {|v| v.last.blank?}
        next if data.blank?
        series_params = {name: well_being.symptom, type: :spline, data: data, marker: {enabled: true, radius: 3}, shadow: true}
        series_params.merge!(yAxis: 1) if params[:treatments]
        f.series series_params
      end

      # Treatments
      if params[:treatments]
        @user.treatments.each do |treatment|
          data = treatment.treatment_logs.where(take_today: true).order('date ASC')
          .map do |v|
            {
              x: v.date.to_time.to_i * 1000,
              y: 4,
              name: "#{l(v.date.to_time, format: :short)}",
              dose: v.try(:current_dose),
              level: v.try(:level).try(:humanize).try(:titleize)
            }
          end
          next if data.blank?
          f.series name: treatment.treatment, id: treatment.treatment, data: data, lineWidth: 0, marker: {enabled: true, radius: 5, symbol: 'circle', lineColor: 'rgba(68, 170, 213, 0.6)'}, shadow: true, yAxis: 0, tooltip: {headerFormat: '<b>{point.key}</b><br>', pointFormat: '{point.series.name}: {point.level}<br>{point.dose}'}, showInLegend: false, visible: false
        end
      end

      # Labs
      @user.labs.each do |lab|
        data = lab.lab_logs.not_blank.order('date ASC')
        .map do |l|
          {
            x: l.date.to_time.to_i * 1000,
            y: l.current_value.to_i,
          }
        end
        max_value = lab.lab_logs.not_blank.maximum('current_value')
        f.series name: lab.name, id: lab.name, data: data,  marker: {enabled: true, radius: 5, symbol: 'circle', lineColor: 'rgba(68, 170, 213, 0.6)'}, shadow: true, yAxis: 2, showInLegend: false, visible: false, max_value: max_value
      end
      f.series name: 'template', id: 'template', data: [],  marker: {enabled: true, radius: 5, symbol: 'circle', lineColor: 'rgba(68, 170, 213, 0.6)'}, shadow: true, yAxis: 2, showInLegend: false, visible: false unless @user.labs.any?

      # Events
      if (@user.id == current_user.try(:id) && !params[:time_series].present?) || (current_user.is_admin? && params[:from] == 'time_series_admin')
        data = []
        Event.unscoped do
          @user.events.order('date ASC').each do |event|
            data << {x: event.date.to_time.to_i * 1000, y: 6, color: '#2C6EB7', name: "#{l(event.date.to_time, format: :short)}", content: event.body}
          end
        end
      end

      f.series name: 'Events', id: 'events', data: data, marker: {enabled: true, symbol: 'circle', radius: 5}, color: '#2C6EB7', tooltip: {headerFormat: '<b>{point.key}</b><br>', pointFormat: '{point.content}'}, lineColor: 'rgba(68, 170, 213, 0.6)' if !params[:time_series].present? || (current_user.is_admin? && params[:from] == 'time_series_admin')

      f.legend enabled: true, maxHeight: 60
      f.exporting buttons: {
        contextButton: {enabled: false},
        exportButton: {text: 'Export', width: 50, x: -70},
        printButton: {text: 'Print', width: 50, x: 0}
      }
      f.rangeSelector inputPosition: {
        align: :left,
        y: 30,
        x: 25
      }, inputEditDateFormat: '%m-%d-%Y'
      f.scrollbar enabled: false
    end
    @symptoms_chart.html_options[:style] = 'height: 800px'
  end

  def activity
    @user = User.find_by_username(params[:username])
    @message = Message.new(to_user_id: @user.id)
    @comment = Comment.new
    activity_logs = ActivityLog.for_user(@user.id).group('activity_id').not_anonymous.recent.limit(300)
    replies = @user.posts.recently_created.limit(300)
    @activity_logs = (activity_logs + replies).sort_by{|r| -r.created_at.to_i}
    @activity_logs = Kaminari.paginate_array(@activity_logs).page(params[:page]).per(20)
  end

  def select_main_condition
    @user_condition = UserCondition.new
    @full_page_view = true
  end

  def profile_photo
    @full_page_view = true if !current_user.finished_profile
  end

  def basic_info
    if current_user.main_condition_id.present?
      @user_condition = UserCondition.new
      @symptom = Symptom.new
      @treatment = Treatment.new

      @full_page_view = true if view_context.after_sign_up_steps?
    else
      current_user.finished_profile = false
      current_user.save
      redirect_to :back, alert: 'You must select a diagnosis to continue.'
    end
  end

  def my_health
    @user_condition = UserCondition.new
    @symptom = Symptom.new
    @treatment = Treatment.new
    @remote = true
    @event = Event.new
    @events = current_user.events
    @p = (@events.count / 15.0).ceil
    @date = Time.now.in_time_zone
  end

  def update

    # After sign up step, when user can post his bio as a topic to the feed
    if view_context.after_sign_up_steps?
      if params[:commit] == 'as_topic' && !user_params[:bio].blank?
        intro_category = PostCategory.find_by_name 'Introductions'
        post = current_user.posts.create title: 'Introduction', content: user_params[:bio], post_category: intro_category
        post.conditions << current_user.main_condition
      end
    end

    current_user.update_attributes(user_params)

    unless current_user.finished_profile?
      cookies[:selected_community] = current_user.try(:main_condition).try(:name)
      current_user.settings.condition_id = current_user.try(:main_condition).try(:slug)
    end

    unless user_params[:profile_photo_file].present?
      Spawnling.new do
        previous_activity = ActivityLog.where(favorite_user_id: current_user.id, activity_type: 'User', created_at: 1.hour.ago..Time.now)
        if previous_activity.any?
          previous_activity.update_all created_at: Time.now, updated_at: Time.now
        else
          current_user.following_users.each do |fuser|
            fuser.following_user.activity_logs.create! activity: current_user, title: "updated their #{view_context.link_to 'Profile', profile_path(current_user.username)}", favorite_user_id: current_user.id, created_at: current_user.updated_at, updated_at: current_user.updated_at
          end
        end
      end
    end
    respond_to do |format|
      format.html do
        if user_params[:profile_photo_file].present?
          redirect_to crop_photo_personal_profile_path
        else
          if view_context.after_sign_up_steps?
            if request.referer =~ /profile_photo/
              redirect_to home_path, notice: 'Your profile was successfully updated'
            elsif request.referer =~ /basic_info/
              redirect_to profile_photo_personal_profile_path
            else
              redirect_to basic_info_personal_profile_path(commit: params[:commit]), notice: 'Your profile was successfully updated'
            end
          else
            if request.referer =~ /select_main_condition/ && params[:user][:main_condition_id].blank?
              flash[:error] = 'You must select a diagnosis to continue.'
              redirect_to select_main_condition_personal_profile_path
            else
              redirect_to home_path
            end
          end
        end
      end
      format.js do
        @user_condition = UserCondition.new
      end
    end
  end

  def crop_photo
    if request.patch?
      current_user.profile_photo.crop!(cropped_photo_params)
      if (30.minutes.ago..Time.zone.now).cover?(current_user.created_at)
        redirect_to my_health_personal_profile_path(finished_profile: true, medical_editor: :conditions)
      else
        redirect_to profile_path(current_user.username), notice: "Photo successfully updated"
      end
    end
  end

  def bookmarks

app/helpers/personal_profile_helper.rb
module PersonalProfileHelper
  def my_health_tabs
    %w(visualize symptoms treatments events labs doctors)
  end

  def get_actual_user(user, actual_user)

    if (user == actual_user) || !user.present?
      actual_user
    else
      user
    end

  end

  def options_for_graph_filter
    options_for_select [%w(Events events), %w(Treatments treatments), %w(Labs labs)]
  end
end

app/views/personal_profiles/_labs.html.haml
.margin-bottom-10= select_tag :with_selected_labs, options_for_select([['', ''], ['Delete Permanently', 'delete']]), style: 'width: 200px'
= button_tag 'Save', class: 'btn btn-success pull-right medical-submit margin-bottom-10', data: {target: '#labs-container form'}
.clearfix
.medical-treatments-table.margin-bottom-10
  .no-padding
    .row.hidden-xs.table-head
      .col-lg-1.col-md-1.col-sm-1
      .col-lg-2.col-md-2.col-sm-2
        Name
      .col-lg-3.col-md-3.col-sm-3
        Current Value
      .col-lg-3.col-md-3.col-sm-3
        Unit of Measurement
  .scrollable-area
    - current_user.labs.includes(:lab_logs).each do |lab|
      %div{id: "lab_#{lab.id}"}
        = form_for lab, url: lab_path(lab), remote: true, html: {class: 'no-padding'} do |f|
          .row.treatment
            = hidden_field_tag :date, (@date ||= Time.zone.now.to_date)
            .col-lg-1.col-md-1.col-sm-1
              = radio_button_tag "bulk_edit_id_#{lab.id}", lab.id, false, class: 'bulk-edit-radio'
            .col-lg-2.col-md-2.col-sm-2
              = f.object.name
            .col-lg-3.col-md-3.col-sm-3
              = f.text_field :current_value, class: 'form-control lab-current-value', placeholder: 'Enter number only', value: lab_value_for_date(lab, :current_value, @date.to_date)
            .col-lg-3.col-md-3.col-sm-3
              = f.text_field :unit, class: 'form-control lab-unit', value: lab_value_for_date(lab, :unit, @date.to_date)

app/views/personal_profiles/_medical_editor.html.haml
- tabs = my_health_tabs
- editor_tab = params.fetch(:medical_editor, tabs.first)

.col-lg-12.col-md-12.col-sm-12.col-xs-12
  %ul#medical_tabs.nav.nav-tabs
    - tabs.each do |tab|
      %li{:class => editor_tab == tab ? 'active' : '', :id => "#{tab}_tab"}
        = link_to my_health_personal_profile_path(medical_editor: tab) do
          = t(tab, scope: %w(medical_editor tabs))

  .tab-content#medical_tabs_content
    - if my_health_tabs.include?(editor_tab)
      .tab-pane{:class => 'active', :id => editor_tab}
        - if (notice = t(editor_tab, scope: %w(medical_editor notices), default: '')).present? && editor_tab != 'treatments' && current_user.settings.send("medical_editor_notice_#{editor_tab}_hidden").blank?
          %br
          .alert.alert-info.notice
            = notice
            = link_to set_setting_path(settings: {"medical_editor_notice_#{editor_tab}_hidden" => true}, flash: false), method: :post, remote: true, 'data-hide' => :alert, class: 'close' do
              = fa_icon 'times-circle'
        = render "#{editor_tab}_container"
.clearfix

app/views/personal_profiles/_personal_profile_tabs.html.haml
.nav.nav-tabs
  %li{class: profile_tab_class('profile')}= link_to 'User Profile', profile_path(@user.username)
  %li{class: profile_tab_class('activity')}= link_to 'User Activity', activity_path(@user.username)
%br  

app/views/personal_profiles/_profile_top.html.haml
%legend
  .col-lg-6.col-md-7.col-sm-12.col-xs-12.no-padding-xs 
    = @user.username
  
  .col-lg-6.col-md-8.col-sm-12.col-xs-12.no-padding-xs 
    - if !(current_user == @user)
      - if current_user.following?(@user)
        = link_to unfollow_user_path(@user), class: 'btn btn-warning btn-xs' do
          %span.glyphicon.glyphicon-th-large
          = 'Remove From My Team'
        &nbsp

      - else
        = link_to follow_user_path(@user), class: 'btn btn-warning btn-xs' do
          %span.glyphicon.glyphicon-th-large
          = 'Add To My Team'
        &nbsp   

      = link_to luv_user_path(@user), class: 'btn btn-danger btn-xs' do
        %span.glyphicon.glyphicon-heart
        LUV
      &nbsp

      = link_to 'javascript:void(0);', class: 'btn btn-info quick-message-link btn-xs' do
        %span.glyphicon.glyphicon-envelope
        Quick Message
      

  .clearfix

app/views/personal_profiles/_symptoms.html.haml
.row.margin-bottom-10
  .col-lg-3.col-md-3.col-sm-3.hidden-xs
  .col-lg-9.col-md-9.col-sm-9.col-xs-12
    = render 'symptoms/gradient'
= button_tag 'Save', class: 'btn btn-success pull-right medical-submit margin-bottom-10', data: {target: '#symptoms_container form'}
.clearfix
.scrollable-area
  .clearfix
  .margin-bottom-10
    = form_for current_user, url: batch_update_symptoms_path, remote: true do |f|
      = render partial: 'symptoms/symptom', collection: current_user.symptoms.notify, locals: {f: f}
  .clearfix
  %h4.treatment-header-taking Not Currently Tracking
  .not-taking-table.margin-bottom-10
    = form_for current_user, url: batch_update_symptoms_path, remote: true do |f|
      = render partial: 'symptoms/symptom', collection: current_user.symptoms.not_notify, locals: {f: f}

app/views/personal_profiles/_treatment.html.haml
%tr.treatment{data: {'treatment-id' => treatment.id}}
  %td.treatment.col-md-5
    = link_to summary_reviews_path(treatment_name: treatment.treatment), target: :_blank do
      = matching_tag(treatment.treatment.to_s)
  %td.selector.col-md-2
    = treatment.level.to_s.titleize
  %td.dosage.col-md-3
    = treatment.current_dose
  %td.reviews.col-md-2
    - if treatment.treatment_review.try(:content).present? && treatment.treatment_review.try(:review).present?
      = link_to "Show Review", post_review_path_helper(treatment.treatment_review.review)

      .modal.hide.fade{id: "review_container_#{treatment.id}"}
        .modal-header
          %button{:type => "button", :class => "close", :"data-dismiss" => "modal", :"aria-hidden" => "true"} &times;
          %h3 #{treatment.treatment.to_s.titleize} - Review
        .modal-body
          = simple_format(treatment.treatment_review.content)
          %br/
          - if treatment.treatment_review.conditions.present?
            %p
              %strong Conditions
            %ul
              - treatment.treatment_review.conditions.each do |condition|
                %li= condition.name
  %td.line.visible-xs.visible-sm

app/views/personal_profiles/activity.js.haml
:plain
  $('#activity_logs_container').append('#{escape_javascript(render(partial: "personal_profiles/activity_log_batch"))}');
  $('.loading_container').hide();

app/views/personal_profiles/my_health.html.haml
- title 'My Health'
- if current_user.finished_profile
  %a{name: "medical_editor"}  
  = render 'medical_editor'
- else
  = form_for current_user, url: personal_profile_path, html: {class: "form-horizontal user-basic-info-form resp-form"} do |f|
    = hidden_field_tag "user[my_health_step]", true
    = f.submit 'Continue', class: 'btn btn-success'

#post_form_container
  = render 'shared/review_form'

app/views/personal_profiles/show.html.haml
%fieldset.padding-10

  = render 'profile_top'

  = render 'personal_profile_tabs'

  .well
    .content
      .span4.compensate
        %p
          %strong Name:
          = @user.full_name
        - unless @user.try(:age).blank?
          %p
            %strong Age:
            #{@user.age} years old
        %p
          %strong Gender:
          #{@user.gender.to_s.titleize}
      .span4
        %p
          %strong Country:
          #{@user.country.try(:name)}
        - if current_user == @user
          %p
            %strong Zip Code:
            #{@user.zipcode}
        %p
          %strong City:
          #{@user.city}
        - unless @user.state.blank?
          %p
            %strong State:
            #{@user.state}
      .span8.compensate
        %p
          %strong About Me:
          = @user.bio
      .clear

  %a{name: "conditions"}
  %fieldset#profile_conditions
    %legend
      Conditions
    .well
      %span.condition
        = matching_tag(@user.main_condition.try(:name).to_s)
      - @user.user_conditions.each do |user_condition|
        - unless user_condition.condition.blank? || user_condition.condition == @user.main_condition
          %span.condition= matching_tag(user_condition.condition.name)

- if @user.symptoms.recent.present?
  %a{name: "symptoms"}
  %fieldset.padding-10
    %legend Symptoms
    .tab-content

      .tab-pane#symptoms_list_container.active
        #symptoms_container.form-horizontal
          .row
            .col-md-3.col-sm-3.table-label.hidden-xs
              Symptom
            .col-md-9.col-sm-9.col-xs-12
              = render 'symptoms/gradient'
          - @user.symptoms.each do |symptom|
            .row.symptom
              .col-md-3.col-sm-3.col-xs-12
                .symptom-name= matching_tag(symptom.symptom.to_s.titleize)

              .col-md-9.col-sm-9.col-xs-12.symptom-severity
                = render 'symptoms/level', symptom: symptom, disabled: true

- if @user.treatments.present?
  %a{name: "treatments"}
  %fieldset.padding-10
    %legend
      Treatments
    .well
      %table.table.show-treatments-table
        %thead
          %tr
            %th.treatment-sort Treatment
            %th.felt-sort How I felt?
            %th.hidden-xs Current Dosage
            %th.hidden-xs Review
        %tbody
          = render partial: 'treatment', collection: @user.treatments.currently_taking.alphabetical
      %h3.centered Not Currently Taking
      %table.table.show-treatments-table
        %tbody
          = render partial: 'treatment', collection: @user.treatments.not_currently_taking.alphabetical

- if @user.doctors.present?
  %a{name: "doctors"}
  %fieldset.padding-10
    %legend
      Doctors
    .well
      %table.table.show-doctors-table
        %thead
          %tr
            %th Doctor
            %th Recommended?
            %th.hidden-xs Location
            %th.hidden-xs Period
            %th.hidden-xs Review
        %tbody
          - @user.doctors.order('name').each do |doctor|
            %tr.doctor
              %td.doctor
                = link_to doctor_reviews_path(query: doctor.name, commit: 'Search', condition_id: 'all', country_id: '', state: ''), target: :_blank do
                  = matching_tag(doctor.name.to_s)
              %td.recommended
                = 'Yes' if doctor.recommended?
                = 'No' if doctor.recommended == false
              %td.location
                = doctor.location
              %td.dates
                - if doctor.started_on.present?
                  = doctors_period doctor
              %td.reviews
                - if doctor.doctor_review.try(:content).present? && doctor.doctor_review.try(:review).present?
                  = link_to "Show Review", post_path(doctor.doctor_review.review)
              %td.line.visible-xs.visible-sm

= render 'profile_quick_message'